"""Start Claude Code with a worked tooling session already in its history

Docs: https://AnswerDotAI.github.io/llmdojo/claudedojo.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_claudedojo.ipynb.

# %% auto #0
__all__ = ['TMPL_PROMPT', 'DROP_ATT', 'GATE_FORBID', 'CAPTURE_SYSP', 'OPENING', 'TMPL_DIR', 'APPEND_PROMPT', 'USAGE',
           'curate_dojo', 'dojo_cid', 'is_clean', 'capture_dojo', 'pick_span', 'mk_template', 'save_template',
           'load_template', 'build_template', 'prep_dojo', 'append_dojo', 'compact_dojo', 'main']

# %% ../nbs/00_claudedojo.ipynb #8602c977
import asyncio, json, os, re, shutil, sys, tempfile, uuid
from importlib.resources import files
from fastcore.utils import *
from llmsurgery.ant import *
from llmsurgery.ipynb import read_ipynb, write_ipynb
from .rules import _state_root

# %% ../nbs/00_claudedojo.ipynb #0c09a7a3
def _is_err(b): return b.get('type')=='tool_result' and b.get('is_error')

def _blocks(r):
    c = r.get('message', {}).get('content', '')
    return [] if isinstance(c, str) else c

# %% ../nbs/00_claudedojo.ipynb #444193d2
TMPL_PROMPT = "Bootstrap and complete the dojo and tell me when you're ready."
DROP_ATT = ('hook_success', 'task_reminder')

def curate_dojo(
    recs, # Captured records, e.g. from `capture_dojo`
):
    "The reproducible template records for a captured dojo run"
    t = strip_think(sess_thread(recs))
    bad = {b['tool_use_id'] for r in t for b in _blocks(r) if _is_err(b)}
    def _keep(r):
        if r.get('type')=='attachment' and r['attachment'].get('type') in DROP_ATT: return False
        return not any(b.get('id') in bad or b.get('tool_use_id') in bad for b in _blocks(r))
    t = reid_recs(t.filter(_keep), 'claudedojo', ts='2026-01-01T00:00:00.000Z')
    p = first(r for r in t if r['type']=='user' and isinstance(r['message']['content'], str))   # the capture prompt, however it was phrased
    p['message']['content'] = TMPL_PROMPT
    return t

def dojo_cid(
    recs, # Template or captured records
):
    "The completion id recorded in the clean-round message"
    return first(m[1] for r in recs if (m := re.search(r'Completion id: ([0-9a-f]{4})', rec_txt(r))))

# %% ../nbs/00_claudedojo.ipynb #96bf7c7b
GATE_FORBID = ('recording a demo', 'these notes')

def _vis(r):
    "An assistant record's visible text, excluding thinking blocks"
    c = r.get('message', {}).get('content', '')
    return c if isinstance(c, str) else ' '.join(b.get('text','') for b in c if b.get('type')=='text')

def is_clean(
    recs, # Captured thread records
    forbid=GATE_FORBID, # Phrases that must not appear in visible assistant text
):
    "Why a captured round can't become a template: a list of problems, empty when the run is clean"
    probs = []
    codes = [c for r in recs for b in _blocks(r) if b.get('type')=='tool_use' and (c := nested_idx(b, 'input', 'code'))]
    if (n := sum('dojo_start(' in c for c in codes)) != 1: probs.append(f'{n} dojo_start calls')
    if (n := sum('dojo_score(' in c for c in codes)) != 1: probs.append(f'{n} dojo_score calls (a clean round scores once, first try)')
    if any('dojo_redo(' in c or 'dojo_resume(' in c for c in codes): probs.append('needed a redo')
    if not any('Clean round' in rec_txt(r) for r in recs if r.get('type')=='user' and rec_role(r)=='tool'): probs.append('no clean score')
    if (n := sum(1 for r in recs for b in _blocks(r) if _is_err(b))): probs.append(f'{n} failed tool calls')
    txt = ' '.join(_vis(r) for r in recs if r.get('type')=='assistant')
    if (bad := [f for f in forbid if f in txt]): probs.append(f"script leaked into visible text: {', '.join(bad)}")
    return probs

# %% ../nbs/00_claudedojo.ipynb #f4e0e6c4
CAPTURE_SYSP = (files('llmdojo')/'dojo_data'/'capture_prompt.md').read_text()

async def capture_dojo(
    d=None, # Template store dir; `TMPL_DIR` if None
    model='fable', # Model for the capture run; the only one smart enough for clean rounds
    effort='medium', # Adaptive thinking effort for the capture run ('low'/'medium'/'high')
    attempts=3, # Gated attempts before giving up
    budget=10.0, # Max USD per attempt
):
    "Play a scripted dojo round headlessly, gate it with `is_clean`, and store the curated template"
    from claude_agent_sdk import query, ClaudeAgentOptions, ResultMessage, AssistantMessage, TextBlock, ToolUseBlock
    for i in range(attempts):
        proj = Path(tempfile.mkdtemp(prefix='claudedojo_'))
        (proj/'pyproject.toml').write_text('[project]\nname = "dojo-capture"\nversion = "0"\n')
        sid = str(uuid.uuid4())
        opts = ClaudeAgentOptions(cwd=proj, session_id=sid, model=model, max_budget_usd=budget, permission_mode='bypassPermissions',
            setting_sources=[], mcp_servers=dict(clikernel=dict(type='stdio', command=shutil.which('clikernel-mcp'))), strict_mcp_config=True,
            thinking=dict(type='adaptive'), effort=effort, env={'LLMDOJO_STATE_DIR': str(proj/'state'), 'MAX_MCP_OUTPUT_TOKENS': '50000'},
            system_prompt=dict(type='preset', preset='claude_code', append=CAPTURE_SYSP))
        cost,err = 0,None
        try:
            async for m in query(prompt=TMPL_PROMPT, options=opts):
                if isinstance(m, ResultMessage): cost = m.total_cost_usd or 0
                elif isinstance(m, AssistantMessage):
                    for b in m.content:
                        if isinstance(b, ToolUseBlock): print('>', str(b.input.get('code', b.input))[:80], flush=True)
                        elif isinstance(b, TextBlock) and b.text.strip(): print('.', b.text.strip()[:80], flush=True)
        except Exception as e: err = f'run failed: {e}'
        recs = [] if err else sess_thread(load_sess(sid, proj))
        probs = [err] if err else is_clean(recs)
        print(f"attempt {i+1}: ${cost:.2f}, {len(recs)} records" + (f", rejected: {'; '.join(probs)}" if probs else ", clean"), flush=True)
        if not probs:
            df = proj/'state'/'doced'/f'{sid}.json'
            ds = json.loads(df.read_text()) if df.exists() else []
            curated = curate_dojo(recs)
            save_template(curated, d, doced=ds)
            dlg = chat2dlg(recs2chat(curated), 'dojo_template', mx=None)
            dlg.meta['llmdojo'] = dict(doced=ds)
            nbf = Path(d or TMPL_DIR)/'template.ipynb'
            write_ipynb(dlg, nbf)
            print(f"stored: cid {dojo_cid(curated)}, {len(curated)} records, {(Path(d or TMPL_DIR)/'template.jsonl').stat().st_size//1024}KB")
            print(f"review dialog: {nbf} - curate it, then claudedojo --build it back into the store")
        shutil.rmtree(proj)
        shutil.rmtree(sess_dir(proj), ignore_errors=True)
        if not probs: return curated
    raise RuntimeError(f'no clean round in {attempts} attempts')

# %% ../nbs/00_claudedojo.ipynb #9069c1a2
def _has_marker(r, marker):
    "Does `r` carry a Bash tool_use whose command contains `marker`?"
    return any(b.get('type')=='tool_use' and b.get('name')=='Bash' and marker in b.get('input', {}).get('command', '') for b in _blocks(r))

def pick_span(
    recs, # Session records, e.g. from `load_sess`
    start='dojo-capture-start', # Marker in the opening Bash sentinel's command
    end='dojo-capture-end', # Marker in the closing Bash sentinel's command
):
    "The records strictly between the last `start` sentinel and the first `end` after it, minus thinking and the sentinels' results"
    idxs = [k for k,r in enumerate(recs) if _has_marker(r, start)]
    if not idxs: raise ValueError(f'no Bash sentinel matches {start!r}')
    i = idxs[-1]
    j = first(k for k,r in enumerate(recs) if k>i and _has_marker(r, end))
    if j is None: raise ValueError(f'no Bash sentinel matches {end!r}')
    tids = {b['id'] for r in (recs[i],recs[j]) for b in _blocks(r) if b.get('type')=='tool_use'}
    return strip_think(L(r for r in recs[i+1:j] if not any(b.get('tool_use_id') in tids for b in _blocks(r))))

# %% ../nbs/00_claudedojo.ipynb #71ddbc0b
OPENING = 'Bootstrapping: the startup script has already run its imports, so I read the tooling docs, check the catalog, then take the dojo.'

def mk_template(
    picked, # Round records, e.g. from `pick_span`
    opening=OPENING, # Reply text preceding the first tool call
    closing="OK I'm ready.", # Reply text ending the round
    doced=None, # Names doc()'d during the round, stored in the dialog's metadata for launch-time doc-state seeding
):
    "A template dialog: `picked` wrapped in `TMPL_PROMPT` and framing text, with tool output untruncated"
    recs = [mk_rec('user', TMPL_PROMPT), mk_rec('assistant', opening), *picked, mk_rec('assistant', closing)]
    dlg = chat2dlg(recs2chat(recs), 'dojo_template', mx=None)
    dlg.meta['llmdojo'] = dict(doced=list(doced or []))
    return dlg

# %% ../nbs/00_claudedojo.ipynb #a288458d
TMPL_DIR = _state_root()/'template'

def _dojo_v():
    from llmdojo.dojo import dojo_version
    return dojo_version()

def save_template(
    recs, # Curated template records
    d=None, # Store dir; `TMPL_DIR` if None
    doced=None, # Names doc()'d during the baked round; the current conversation's doc-state if None
):
    "Write the template and its metadata to the store"
    if doced is None:
        from llmdojo.rules import doced as _cur
        doced = _cur()
    d = Path(d or TMPL_DIR)
    d.mkdir(parents=True, exist_ok=True)
    (d/'template.jsonl').write_text(''.join(json.dumps(obj2dict(r))+'\n' for r in recs))
    (d/'meta.json').write_text(json.dumps(dict(cid=dojo_cid(recs), v=_dojo_v(), doced=doced)))

def load_template(
    d=None, # Store dir; `TMPL_DIR` if None
):
    "The stored template records and metadata"
    d = Path(d or TMPL_DIR)
    return [json.loads(l) for l in (d/'template.jsonl').read_text().splitlines()], json.loads((d/'meta.json').read_text())

# %% ../nbs/00_claudedojo.ipynb #658ba7f7
def build_template(
    src, # Path to a template dialog .ipynb
    d=None, # Store dir; `TMPL_DIR` if None
    cwd='.', # Project directory recorded in the records
):
    "Convert a template dialog into the store; the dialog's `llmdojo.doced` metadata rides along for launch-time doc-state seeding"
    dlg = read_ipynb(str(src))
    save_template(msgs2recs(dlg2msgs(dlg), key='claudedojo', cwd=str(cwd), model=None), d,
        doced=nested_idx(dlg.meta, 'llmdojo', 'doced'))

# %% ../nbs/00_claudedojo.ipynb #67610ec0
def _load_reg(d):
    "Load the store (built from the packaged dialog if empty), warn on version skew, and register its completion id"
    if not (Path(d or TMPL_DIR)/'template.jsonl').exists():
        build_template(files('llmdojo')/'dojo_data'/'dojo_template.ipynb', d)   # first use on this machine: build the store from the packaged dialog
    recs,meta = load_template(d)
    if meta['v'] != _dojo_v(): print(f"claudedojo: template built under {meta['v']} but installed tooling is {_dojo_v()}; the baked round will not validate. Rebuild with claudedojo --build <dialog>, or refresh unattended with claudedojo --capture.", file=sys.stderr)
    from llmdojo.dojo import register_completion
    register_completion(meta['cid'], meta['v'])
    return recs,meta

def _seed_doced(sid, names, merge=False):
    "Make the baked round's 'Doc-state is intact' true for conversation `sid`"
    d = _state_root()/'doced'
    d.mkdir(parents=True, exist_ok=True)
    f = d/f'{sid}.json'
    if merge and f.exists(): names = set(names) | set(json.loads(f.read_text()))
    f.write_text(json.dumps(sorted(names)))

def prep_dojo(
    cwd=None, # Project to start in; the current directory if None
    d=None, # Template store dir; `TMPL_DIR` if None
):
    "Write the template session for `cwd`, register its completion id, seed its doc-state, and return the session id to resume"
    recs,meta = _load_reg(d)
    sid = save_sess(recs, cwd=cwd, ts=True)
    if ds := meta.get('doced'): _seed_doced(sid, ds)
    return sid

# %% ../nbs/00_claudedojo.ipynb #bb20faff
APPEND_PROMPT = "We've compacted - run the dojo round again and tell me when you're ready."

def append_dojo(
    sid=None, # Session id or name to append to; the project's newest transcript if None
    cwd=None, # Project directory; the current directory if None
    d=None, # Template store dir; `TMPL_DIR` if None
):
    "Append the template round to session `sid` (e.g. after a compaction), re-seed doc-state, and return `sid` to resume"
    trecs,meta = _load_reg(d)
    sid,path = resolve_session(sid, cwd or '.')
    tail = load_recs(path)
    trecs = reid_recs(trecs, f'append:{sid}:{len(tail)}')   # fresh salt per append, so repeated splices never collide
    trecs[0]['message']['content'] = APPEND_PROMPT
    append_sess(trecs, sid, cwd, ts=True)
    _seed_doced(sid, meta.get('doced') or [], merge=True)   # merge: after a compact the hook truncated the record, so this is just the round's list
    return sid

# %% ../nbs/00_claudedojo.ipynb #aa9b31fe
def compact_dojo(
    sid=None, # Session id or name to compact; the project's newest transcript if None
    cwd=None, # Project directory; the current directory if None
    d=None, # Template store dir; `TMPL_DIR` if None
):
    "Synthetically compact a session with the compact DSL, then append the template round; returns the session id"
    c = compact_session(sid, cwd or '.')
    return append_dojo(c.sid, cwd, d)

# %% ../nbs/00_claudedojo.ipynb #29c39ffd
USAGE = """usage: claudedojo [--build <dialog.ipynb> | --capture [model [effort]] | -r [sessid] | --compact [sessid] | <claude args...>]
Prepare and print a Claude session id when called without arguments.
  --build <dialog.ipynb>      convert a template dialog and store it, instead of launching
  --capture [model [effort]]  play a scripted round headlessly (Agent SDK), gate it with is_clean, and store it (default: fable, medium)
  -r [sess]                   append the round to an existing session, by id or name (the project's newest if omitted), and print its id; after a compaction: claude -r $(claudedojo -r)
  --compact [sess]            synthetically compact a session with the compact DSL and append the round: claude -r $(claudedojo --compact)
  <claude args...>            anything else starts Claude with a prepared session and passes through the arguments"""

def main():
    "CLI entry point; run `claudedojo -h` for usage"
    args = sys.argv[1:]
    if args[:1] in (['-h'], ['--help']) or (args[:1]==['--build'] and len(args)!=2) \
        or (args[:1]==['--capture'] and len(args)>3) or (args[:1] in (['-r'],['--compact']) and len(args)>2): return print(USAGE)
    if not args: return print(prep_dojo())
    if args[:1] == ['--build']: return build_template(args[1], cwd=Path.cwd())
    if args[:1] == ['-r']: return print(append_dojo(args[1] if len(args)==2 else None))
    if args[:1] == ['--compact']: return print(compact_dojo(args[1] if len(args)==2 else None))
    if args[:1] == ['--capture']:
        asyncio.run(capture_dojo(model=args[1] if len(args)>1 else 'fable', effort=args[2] if len(args)>2 else 'medium'))   # discard the records: the console script sys.exit()s main's return value
        return
    os.execvp('claude', ['claude', '-r', prep_dojo(), *args])
