"""Start Claude Code with a worked tooling session already in its history

Docs: https://AnswerDotAI.github.io/llmdojo/claudedojo.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_claudedojo.ipynb.

# %% auto #0
__all__ = ['DROP_ATT', 'OPENING', 'TMPL_DIR', 'capture_span', 'curate_dojo', 'dojo_cid', 'is_clean', 'mk_template',
           'save_template', 'load_template', 'build_template', 'capture_current', 'capture_dojo', 'prep_dojo',
           'append_dojo', 'strip_dojo', 'compact_dojo', 'main']

# %% ../nbs/00_claudedojo.ipynb #8602c977
import asyncio, json, os, re, shutil, sys, tempfile, uuid
from importlib.resources import files
from fastcore.utils import *
from fastcore.script import call_parse
from llmsurgery.ant import *
from aidialog.ipynb import read_ipynb, write_ipynb
from aidialog.hist import chat2dlg
from .rules import _state_root
from .tmpl import *
from .tmpl import _dojo_v, _seed_doced, _START_RE, _turns

# %% ../nbs/00_claudedojo.ipynb #0c09a7a3
def _is_err(b): return b.get('type')=='tool_result' and b.get('is_error')

def _blocks(r):
    c = r.get('message', {}).get('content', '')
    return [] if isinstance(c, str) else c

def _cells(recs):
    "Kernel cell sources of the tool calls in `recs`, in order ('' for non-kernel calls)"
    return [nested_idx(b, 'input', 'code') or '' for r in recs for b in _blocks(r) if b.get('type')=='tool_use']

# %% ../nbs/00_claudedojo.ipynb #444193d2
DROP_ATT = ('hook_success', 'task_reminder')

def capture_span(
    recs, # Session records, e.g. from `load_sess`
):
    "The thread records of the captured round: bootstrap docs through the first score of the last dealt round"
    t = strip_think(sess_thread(recs))
    calls = [(k, nested_idx(b,'input','code') or '', b['id']) for k,r in enumerate(t) for b in _blocks(r) if b.get('type')=='tool_use']
    i,j = capture_slice([c for _,c,_ in calls])
    kend = first(k for k,r in enumerate(t) if any(b.get('tool_use_id')==calls[j][2] for b in _blocks(r)))
    return L(t[calls[i][0]:kend+1])

def curate_dojo(
    recs, # Session records containing a played round, e.g. from `capture_dojo`'s child
):
    "The reproducible records of the captured round: its span, minus mid-round prompts, attachments, and failed calls, deterministically re-id'd"
    t = capture_span(recs)
    bad = {b['tool_use_id'] for r in t for b in _blocks(r) if _is_err(b)}
    def _keep(r):
        if r.get('type')=='attachment' and r['attachment'].get('type') in DROP_ATT: return False
        if r.get('type')=='user' and rec_role(r)!='tool': return False
        return not any(b.get('id') in bad or b.get('tool_use_id') in bad for b in _blocks(r))
    return reid_recs(t.filter(_keep), 'claudedojo', ts='2026-01-01T00:00:00.000Z')

def dojo_cid(
    recs, # Template or captured records
):
    "The completion id recorded in the clean-round message"
    return find_cid(map(rec_txt, recs))

# %% ../nbs/00_claudedojo.ipynb #96bf7c7b
def _vis(r):
    "An assistant record's visible text, excluding thinking blocks"
    c = r.get('message', {}).get('content', '')
    return c if isinstance(c, str) else ' '.join(b.get('text','') for b in c if b.get('type')=='text')

def is_clean(
    recs, # Captured thread records
    forbid=GATE_FORBID, # Phrases that must not appear in visible assistant text
):
    "Why a captured round can't become a template: a list of problems, empty when the run is clean"
    cells = [c for r in recs for b in _blocks(r) if b.get('type')=='tool_use' and (c := nested_idx(b, 'input', 'code'))]
    outs = [rec_txt(r) for r in recs if r.get('type')=='user' and rec_role(r)=='tool']
    vis = ' '.join(_vis(r) for r in recs if r.get('type')=='assistant')
    probs = round_gates(cells, outs, vis, forbid)
    if (n := sum(1 for r in recs for b in _blocks(r) if _is_err(b))): probs.append(f'{n} failed tool calls')
    return probs

# %% ../nbs/00_claudedojo.ipynb #71ddbc0b
OPENING = 'Bootstrapping: the startup script has already run its imports, so I read the tooling docs, check the catalog, then take the dojo.'

def mk_template(
    picked, # Round records, e.g. from `curate_dojo`
    opening=OPENING, # Reply text preceding the first tool call
    closing="OK I'm ready.", # Reply text ending the round
    doced=None, # Names doc()'d during the round, stored in the dialog's metadata for launch-time doc-state seeding
):
    "A template dialog: `picked` wrapped in `TMPL_PROMPT` and framing text, with tool output untruncated"
    recs = [mk_rec('user', TMPL_PROMPT), mk_rec('assistant', opening), *picked, mk_rec('assistant', closing)]
    dlg = chat2dlg(recs2chat(recs), 'dojo_template', mx=None)
    dlg.meta['llmdojo'] = dict(doced=list(doced or []))
    return dlg

# %% ../nbs/00_claudedojo.ipynb #a288458d
TMPL_DIR = files('llmdojo')/'dojo_data'/'claude_store'   # package data: compiled by dojobuild, shipped with the code

def save_template(
    recs, # Curated template records
    d=None, # Store dir; `TMPL_DIR` if None
    doced=None, # Names doc()'d during the baked round; the current conversation's doc-state if None
):
    "Write the template and its metadata to the store"
    save_store(Path(d or TMPL_DIR), recs, dojo_cid(recs), doced)

def load_template(
    d=None, # Store dir; `TMPL_DIR` if None
):
    "The stored template records and metadata"
    return load_store(Path(d or TMPL_DIR))

# %% ../nbs/00_claudedojo.ipynb #658ba7f7
def build_template(
    src, # Path to a template dialog .ipynb
    d=None, # Store dir; `TMPL_DIR` if None
    cwd='.', # Project directory recorded in the records
):
    "Convert a template dialog into the store; the dialog's `llmdojo.doced` metadata rides along for launch-time doc-state seeding"
    dlg = read_ipynb(str(src))
    save_template(msgs2recs(dlg2msgs(dlg), key='claudedojo', cwd=str(cwd), model=None), d,
        doced=nested_idx(dlg.meta, 'llmdojo', 'doced'))

# %% ../nbs/00_claudedojo.ipynb #9069c1a2
def capture_current(
    sid=None, # Session id or name; the project's newest transcript if None
    cwd=None, # Project directory; the current directory if None
    d=None, # Template store dir; `TMPL_DIR` if None
    docs=None, # Documented names; derived from the round's `doc(...)` calls if None
):
    "Gate an existing session's clean round and store its template"
    selected = curate_dojo(load_sess(sid, cwd))
    if probs := is_clean(selected): raise ValueError('; '.join(probs))
    if docs is None: docs = doced_names(_cells(selected))
    dlg = canon_tmpl(mk_template(selected, doced=docs))
    save_template(msgs2recs(dlg2msgs(dlg), key='claudedojo', model=None), d, doced=docs)
    write_ipynb(dlg, Path(d or TMPL_DIR)/'template.ipynb')
    return dlg

# %% ../nbs/00_claudedojo.ipynb #f4e0e6c4
async def capture_dojo(
    d=None, # Template store dir; `TMPL_DIR` if None
    model='fable', # Model for the capture run; the only one smart enough for clean rounds
    effort='medium', # Adaptive thinking effort for the capture run ('low'/'medium'/'high')
    attempts=3, # Gated attempts before giving up
    budget=10.0, # Max USD per attempt
):
    "Play a scripted dojo round headlessly, gate it with `is_clean`, and store the curated template"
    from claude_agent_sdk import query, ClaudeAgentOptions, ResultMessage, AssistantMessage, TextBlock, ToolUseBlock
    for i in range(attempts):
        proj = Path(tempfile.mkdtemp(prefix='claudedojo_'))
        (proj/'pyproject.toml').write_text('[project]\nname = "dojo-capture"\nversion = "0"\n')
        sid = str(uuid.uuid4())
        opts = ClaudeAgentOptions(cwd=proj, session_id=sid, model=model, max_budget_usd=budget, permission_mode='bypassPermissions',
            setting_sources=[], mcp_servers=dict(clikernel=dict(type='stdio', command=shutil.which('clikernel-mcp'))), strict_mcp_config=True,
            thinking=dict(type='adaptive'), effort=effort, env={'LLMDOJO_STATE_DIR': str(proj/'state'), 'MAX_MCP_OUTPUT_TOKENS': '50000'},
            system_prompt=dict(type='preset', preset='claude_code', append=CAPTURE_SCRIPT))
        cost,err = 0,None
        try:
            async for m in query(prompt=TMPL_PROMPT, options=opts):
                if isinstance(m, ResultMessage): cost = m.total_cost_usd or 0
                elif isinstance(m, AssistantMessage):
                    for b in m.content:
                        if isinstance(b, ToolUseBlock): print('>', str(b.input.get('code', b.input))[:80], flush=True)
                        elif isinstance(b, TextBlock) and b.text.strip(): print('.', b.text.strip()[:80], flush=True)
        except Exception as e: err = f'run failed: {e}'
        recs = [] if err else sess_thread(load_sess(sid, proj))
        probs = [err] if err else is_clean(recs)
        print(f"attempt {i+1}: ${cost:.2f}, {len(recs)} records" + (f", rejected: {'; '.join(probs)}" if probs else ", clean"), flush=True)
        if not probs:
            tdlg = capture_current(sid, proj, d)
            print(f"stored: cid {load_template(d)[1]['cid']}, {(Path(d or TMPL_DIR)/'template.jsonl').stat().st_size//1024}KB")
            print(f"review dialog: {Path(d or TMPL_DIR)/'template.ipynb'} - curate it, then rebuild the stores with dojobuild --claude (and --codex)")
        shutil.rmtree(proj)
        shutil.rmtree(sess_dir(proj), ignore_errors=True)
        if not probs: return tdlg
    raise RuntimeError(f'no clean round in {attempts} attempts')

# %% ../nbs/00_claudedojo.ipynb #67610ec0
def _load_reg(d):
    "The loaded packaged store, registered, via the shared `load_reg`"
    return load_reg(d, TMPL_DIR, 'claudedojo')

def prep_dojo(
    cwd=None, # Project to start in; the current directory if None
    d=None, # Template store dir; `TMPL_DIR` if None
):
    "Write the template session for `cwd`, register its completion id, seed its doc-state, and return the session id to resume"
    recs,meta = _load_reg(d)
    sid = save_sess(recs, cwd=cwd, ts=True)
    if ds := meta.get('doced'): _seed_doced(sid, ds)
    return sid

# %% ../nbs/00_claudedojo.ipynb #bb20faff
def append_dojo(
    sid=None, # Session id or name to append to; the project's newest transcript if None
    cwd=None, # Project directory; the current directory if None
    d=None, # Template store dir; `TMPL_DIR` if None
):
    "Append the template round to session `sid` (e.g. after a compaction), re-seed doc-state, and return `sid` to resume"
    trecs,meta = _load_reg(d)
    sid,path = resolve_session(sid, cwd or '.')
    tail = load_recs(path)
    trecs = reid_recs(trecs, f'append:{sid}:{len(tail)}')   # fresh salt per append, so repeated splices never collide
    trecs[0]['message']['content'] = APPEND_PROMPT
    append_sess(trecs, sid, cwd, ts=True)
    _seed_doced(sid, meta.get('doced') or [], merge=True)   # merge: after a compact the hook truncated the record, so this is just the round's list
    return sid

# %% ../nbs/00_claudedojo.ipynb #cff4225e
def _is_prompt(r): return r.get('type')=='user' and rec_role(r)=='user'

def _dealt(t): return any(re.match(_START_RE, nested_idx(b,'input','code') or '') for r in t for b in _blocks(r))

def strip_dojo(
    recs, # Session records, e.g. from `load_sess`
):
    "Copy of `recs` without the user turns that dealt a round (bare `dojo_start()`)"
    return _turns(recs, _is_prompt).filter(_dealt, negate=True).concat()

# %% ../nbs/00_claudedojo.ipynb #aa9b31fe
def compact_dojo(
    sid=None, # Session id or name to compact; the project's newest transcript if None
    cwd=None, # Project directory; the current directory if None
    d=None, # Template store dir; `TMPL_DIR` if None
):
    "Synthetically compact a session with the compact DSL (previous dojo rounds removed first), then append the template round; returns the session id"
    sid,_ = resolve_session(sid, cwd or '.')
    recs = load_sess(sid, cwd)
    if len(recs) > len(stripped := strip_dojo(recs)) > 0: save_sess(stripped, sid, cwd)   # a round-only session has nothing else to compact: leave it whole
    c = compact_session(sid, cwd or '.')
    return append_dojo(c.sid, cwd, d)

# %% ../nbs/00_claudedojo.ipynb #29c39ffd
@call_parse(nested=True, pos=['sess'])
def main(
    sess:str=None, # Session id or name; the project's newest transcript where omitted
    Resume:bool=False, # Append the round to an existing session after a compaction, then resume it
    Compact:bool=False, # Synthetically compact the session with the compact DSL, then append the round and resume
    sid:bool=False, # Print the prepared session id instead of launching claude
    capture:bool=False, # Play a scripted round headlessly (Agent SDK), gate it with is_clean, and store it
    current:bool=False, # Store the clean round an existing session already played (`capture_current`)
    capture_model:str='fable', # Model for --capture; the only one smart enough for clean rounds
    capture_effort:str='medium', # Adaptive thinking effort for --capture ('low'/'medium'/'high')
):
    "Prepare a session opening with the worked round and launch `claude` on it; template maintenance is `dojobuild`"
    if capture: return asyncio.run(capture_dojo(model=capture_model, effort=capture_effort))
    if current: return capture_current(sess)
    if Resume:
        try: s = append_dojo(sess)
        except FileNotFoundError as e: sys.exit(f'{e}\nNo session to append to; run claudedojo without -r to prepare a fresh one')
    elif Compact: s = compact_dojo(sess)
    else:
        if sess: sys.exit(f"unexpected argument {sess!r}: a fresh launch takes no session, and claude flag values need --flag=value form")
        s = prep_dojo()
    if sid: return print(s)
    os.execvp('claude', ['claude', *launch_config('claude'), '-r', s, *sys.argv[1:]])
