"""Spawn a headless Claude child on this session's compacted history

Docs: https://AnswerDotAI.github.io/llmdojo/claudesub.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_claudesub.ipynb.

# %% auto #0
__all__ = ['PROTOCOL', 'parent_sid', 'dojo_cid', 'prep_sub', 'sub_cmd', 'run_sub', 'main']

# %% ../nbs/03_claudesub.ipynb #37a44372
import json, os, subprocess, sys
from fastcore.utils import *
from fastcore.script import call_parse
from fastclaude.session import *
from fastclaude.core import claude_env
from llmsurgery.ant import prepare_compaction
from .dojo import _completions, dojo_version
from .tmpl import launch_config

# %% ../nbs/03_claudesub.ipynb #92c74735
def parent_sid(
    cwd=None, # Project directory; the current directory if None
):
    "The launching session, from `CLAUDE_CODE_SESSION_ID`; an error rather than a guess when it is unset or names no transcript"
    sid = os.environ.get('CLAUDE_CODE_SESSION_ID')
    if not sid: raise RuntimeError('CLAUDE_CODE_SESSION_ID is unset: claudesub runs from inside a Claude Code session')
    if not (sess_dir(cwd)/f'{sid}.jsonl').exists(): raise FileNotFoundError(f'No transcript for session {sid} under {sess_dir(cwd)}')
    return sid

def dojo_cid():
    "The newest clean-round completion id minted under the current dojo version, or None"
    v = dojo_version()
    ids = [(o['t'],k) for k,o in _completions().items() if o.get('v')==v]
    return max(ids)[1] if ids else None

# %% ../nbs/03_claudesub.ipynb #73069149
def prep_sub(
    sid=None, # Parent session id; `parent_sid()` if None
    cwd=None, # Project directory; the current directory if None
):
    "Write a session holding only the parent's compacted history, returning its id for the child to resume"
    c = prepare_compaction(sid or parent_sid(cwd), cwd or '.')
    return save_sess(list(c.records), cwd=cwd, ts=True)

# %% ../nbs/03_claudesub.ipynb #47df8e27
PROTOCOL = """You are a subagent spawned by another Claude Code session with `claudesub`. The history above is that session's compacted transcript: you hold its decisions and evidence, but none of its kernel state. Your clikernel kernel is your own; no other session shares it. No person is watching, so never wait for an answer or ask a question mid-task: if you are blocked, stop and report exactly what you need, and the parent can resume you with `claudesub -r <your session id> '<answer>'`, which restarts your kernel, so finish whatever does not depend on the answer before you stop. Bootstrap with dojo_start({cid!r}). Then do the directive, and end with a report the parent can act on without reading your transcript: what you did, what you found, and anything left undone."""

def sub_cmd(
    directive, # The child's task
    sid, # Session id for the child to resume
    cid=None, # Dojo completion id to hand the child; `dojo_cid()` if None
    extra=(), # Further `claude` arguments, after the standing ones from `launch_config`
):
    "argv for the headless child: resume `sid` with `directive`, streaming events as JSON lines; refuses without a clean-round id, since a child never plays the round"
    cid = cid or dojo_cid()
    if not cid: raise RuntimeError('No clean dojo round is on record for this tooling version: play one in the parent session first')
    return ['claude', '-p', directive, f'--resume={sid}', '--output-format=stream-json', '--verbose',
        '--append-system-prompt', PROTOCOL.format(cid=cid), *launch_config('claude'), *extra]

# %% ../nbs/03_claudesub.ipynb #e02e4bed
def run_sub(
    argv, # The child command, from `sub_cmd`
    quiet=False, # Print only the final report and footer, not the child's text as it arrives?
    cwd=None, # Directory the child runs in; the current directory if None
):
    "Run the child, streaming its text, and return its result event"
    p = subprocess.Popen(argv, stdout=subprocess.PIPE, text=True, env=claude_env(), cwd=cwd)
    res = None
    for line in p.stdout:
        try: e = json.loads(line)
        except json.JSONDecodeError: continue
        if e.get('type')=='result': res = e
        elif e.get('type')=='assistant' and not quiet:
            for b in e['message'].get('content', []):
                if b.get('type')=='text' and b['text'].strip(): print(b['text'].strip(), flush=True)
    p.wait()
    if res is None: raise RuntimeError(f'claude exited {p.returncode} without a result')
    if quiet: print(res.get('result', ''))
    print(f"[claudesub {res['subtype']}] session {res['session_id']}, {res['num_turns']} turns, ${res.get('total_cost_usd', 0):.2f}", flush=True)
    return res

# %% ../nbs/03_claudesub.ipynb #5e40a1d7
@call_parse(nested=True, pos=['directive'])
def main(
    directive:str, # The child's task
    Resume:str=None, # A child session id to continue with `directive` as its next prompt, instead of spawning from this session
    sid:bool=False, # Print the prepared child session id instead of launching
    Quiet:bool=False, # Print only the child's final report, not its progress text
    cwd:str=None, # Project directory to work from, for the parent lookup, the child session, and the child itself; the current directory if None
):
    "Spawn a headless Claude child on this session's compacted history and stream its text; unrecognized `--flag=value` args go to `claude`"
    if cwd: os.chdir(cwd)
    s = Resume or prep_sub()
    if sid: return print(s)
    res = run_sub(sub_cmd(directive, s, extra=sys.argv[1:]), quiet=Quiet)
    if res['subtype'] != 'success': sys.exit(1)
