"""Pre-baked Codex sessions that demonstrate a clean llmdojo round

Docs: https://AnswerDotAI.github.io/llmdojo/codexdojo.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_codexdojo.ipynb.

# %% auto #0
__all__ = ['OPENING', 'SAMPLE_POLICY', 'TMPL_DIR', 'collapse_deferred', 'pick_calls', 'pick_turns', 'dojo_round', 'curate_dojo',
           'dojo_cid', 'is_clean', 'capture_current', 'capture_dojo', 'mk_template', 'dojo_sample', 'save_template',
           'load_template', 'build_template', 'prep_dojo', 'append_dojo', 'strip_dojo', 'compact_dojo', 'main']

# %% ../nbs/01_codexdojo.ipynb #db524999
import asyncio, json, os, re, subprocess, sys, tempfile, uuid
from importlib.resources import files
from fastcore.utils import *
from fastcore.script import call_parse
from llmsurgery.oai import *
from llmsurgery.compact import compact_chat
from aidialog.ipynb import read_ipynb, write_ipynb
from .rules import _state_root
from .tmpl import *
from .tmpl import _dojo_v, _seed_doced, _START_RE, _turns

# %% ../nbs/01_codexdojo.ipynb #1f05a641
def _items(src):
    "Responses items from either rollout records or an item sequence"
    src = L(src)
    return response_items(src) if any(x.get('type')=='response_item' for x in src) else L(obj2dict(x) for x in src)

def _out_text(item):
    out = item.get('output','')
    if isinstance(out,str): return out
    return '\n'.join(x.get('text','') for x in out if x.get('type') in ('input_text','output_text'))

def _logical(item): return parse_exec(item.get('input','')) if item.get('type')=='custom_tool_call' else None

def _cell(item):
    p = _logical(item)
    return p.arguments.get('code','') if p and p.name=='tools.mcp__clikernel__execute' else ''

# %% ../nbs/01_codexdojo.ipynb #786bd5fb
def collapse_deferred(src):
    "Custom call/result pairs, replacing host-level deferred waits with their final result"
    items,out = _items(src),[]
    cis = [i for i,x in enumerate(items) if x.get('type')=='custom_tool_call']
    for n,i in enumerate(cis):
        call,end = items[i],cis[n+1] if n+1<len(cis) else len(items)
        seg = items[i+1:end]
        result = first(x for x in seg if x.get('type')=='custom_tool_call_output' and x.get('call_id')==call.get('call_id'))
        if not result: continue
        if 'Script running with cell ID' in _out_text(result):
            waits = [x for x in seg if x.get('type')=='function_call' and x.get('name')=='wait']
            if waits:
                final = first(x for x in seg if x.get('type')=='function_call_output' and x.get('call_id')==waits[-1].get('call_id'))
                if final: result = codex_custom_output(call['call_id'], final.get('output',''))
        out += [call,result]
    return L(out)

# %% ../nbs/01_codexdojo.ipynb #629226fd
def pick_calls(
    src, # Rollout records or Responses items
    *specs, # `(logical_name, cell_source_or_argument_subset)` pairs
):
    "The last matching custom call/result pair for each spec, in spec order"
    pairs = collapse_deferred(src)
    calls = [(pairs[i],pairs[i+1],_logical(pairs[i])) for i in range(0,len(pairs),2)]
    out = []
    for name,want in specs:
        cand = [(c,r,p) for c,r,p in calls if p and p.name==name]
        if isinstance(want,dict): cand = [(c,r,p) for c,r,p in cand if all(p.arguments.get(k)==v for k,v in want.items())]
        else:
            exact = [(c,r,p) for c,r,p in cand if _cell(c)==want]
            cand = exact or [(c,r,p) for c,r,p in cand if _cell(c).startswith(want)]
        if not cand: raise ValueError(f'no custom call matches {name} {want!r}')
        out += cand[-1][:2]
    return L(out)

# %% ../nbs/01_codexdojo.ipynb #9e66e463
def pick_turns(
    src, # Rollout records or Responses items
    *cells, # Kernel cell sources: matched exactly, else as a prefix; the last match wins
):
    "The clikernel MCP call/result pairs for `cells`, in that order"
    return pick_calls(src, *((('tools.mcp__clikernel__execute',c) for c in cells)))

# %% ../nbs/01_codexdojo.ipynb #2dbf7eb2
def dojo_round(src):
    "The last complete dojo_start()/dojo_score() custom-tool span"
    pairs = collapse_deferred(src)
    calls = pairs[::2]
    starts = [i for i,c in enumerate(calls) if re.match(_START_RE, _cell(c))]
    if not starts: raise ValueError('no dojo_start() call')
    start = starts[-1]
    scores = [i for i,c in enumerate(calls[start:],start) if re.match(r'^dojo_score\(', _cell(c))]
    if not scores: raise ValueError('no dojo_score() after dojo_start()')
    return pairs[start*2:(scores[0]+1)*2]

# %% ../nbs/01_codexdojo.ipynb #c4ac3c42
def curate_dojo(src):
    "The reproducible custom-tool items for the last complete dojo round"
    return reid_items(dojo_round(src), 'codexdojo')

# %% ../nbs/01_codexdojo.ipynb #705852d8
def dojo_cid(items):
    "The completion id recorded in the clean-round output"
    return find_cid(map(item_txt, items))

# %% ../nbs/01_codexdojo.ipynb #ce3882cc
def is_clean(
    items, # A curated dojo round
    forbid=GATE_FORBID, # Phrases that must not appear in visible assistant text
):
    "Why a captured round cannot become a template; empty means clean"
    items = _items(items)
    calls = [x for x in items if x.get('type')=='custom_tool_call']
    outs = [_out_text(x) for x in items if x.get('type')=='custom_tool_call_output']
    visible = ' '.join(item_txt(x) for x in items if x.get('type')=='message' and x.get('role')=='assistant')
    probs = round_gates([_cell(x) for x in calls], outs, visible, forbid)
    if (n:=sum('\nTraceback (most recent call last):' in o for o in outs)): probs.append(f'{n} failed tool calls')
    ids = {x.get('call_id') for x in items if x.get('type')=='custom_tool_call_output'}
    if (n:=sum(x.get('call_id') not in ids for x in calls)): probs.append(f'{n} calls without results')
    return probs

# %% ../nbs/01_codexdojo.ipynb #fce1bcb2
def _capture_span(src):
    "Native custom-call pairs from the bootstrap docs through the first dojo score"
    items = _items(src)
    starts = [i for i,x in enumerate(items) if re.match(_START_RE,_cell(x))]
    if not starts: raise ValueError('no dojo_start() call')
    start = starts[-1]
    users = [i for i,x in enumerate(items[:start]) if x.get('type')=='message' and x.get('role')=='user']
    if not users: raise ValueError('no user message before dojo_start()')
    end = first((i for i,x in enumerate(items[start+1:],start+1) if x.get('type')=='message' and x.get('role')=='user'),len(items))
    pairs = collapse_deferred(items[users[-1]+1:end])
    i,j = capture_slice([_cell(x) for x in pairs[::2]])
    return pairs[i*2:(j+1)*2]

def capture_current(
    ref=None, # Codex thread UUID; current thread if None
    d=None, # Template store dir; `TMPL_DIR` if None
    docs=None, # Documented names; derived from captured `doc(...)` calls if None
):
    "Gate an existing Codex thread's clean round and store its native template"
    selected = reid_items(_capture_span(response_items(load_rollout(ref))),'codexdojo')
    if probs:=is_clean(selected): raise ValueError('; '.join(probs))
    if docs is None: docs = doced_names([_cell(x) for x in selected])
    dlg = canon_tmpl(mk_template(selected,doced=docs))
    save_template(dlg2items(dlg),d,doced=docs)
    write_ipynb(dlg,Path(d or TMPL_DIR)/'template.ipynb')
    return dlg

def capture_dojo(
    d=None, # Template store dir; `TMPL_DIR` if None
):
    "Run a clean dojo in a bare Codex child and store its review dialog"
    with tempfile.TemporaryDirectory(prefix='codexdojo_') as td:
        proj = Path(td)
        (proj/'pyproject.toml').write_text('[project]\nname = "dojo-capture"\nversion = "0"\n')
        (proj/'AGENTS.md').write_text(CAPTURE_SCRIPT)
        env = os.environ | {'LLMDOJO_STATE_DIR': str(proj/'state')}
        cmd = ['codex','-a','never','-s','workspace-write','exec','--json','--skip-git-repo-check','-C',str(proj),TMPL_PROMPT]
        proc = subprocess.Popen(cmd,stdout=subprocess.PIPE,text=True,env=env)
        sid = None
        for line in proc.stdout:
            event = json.loads(line)
            if event.get('type')=='thread.started':
                sid = event['thread_id']
                print(f'thread: {sid}',flush=True)
            elif event.get('type')=='item.completed':
                it = event.get('item',{})
                typ = it.get('type')
                if typ=='agent_message': print(it['text'],flush=True)
                elif typ!='reasoning':
                    c = parse_exec(it.get('input') or '')
                    desc = c.arguments.get('code',str(c.arguments)).splitlines()[0] if c else truncstr(json.dumps(it),160)
                    print(f'[{typ}] {desc}',flush=True)
        if rc:=proc.wait(): raise subprocess.CalledProcessError(rc,cmd)
        if not sid: raise RuntimeError('capture produced no thread id')
        return capture_current(sid,d)

# %% ../nbs/01_codexdojo.ipynb #8c6b39a0
OPENING = 'Bootstrapping: I read the tooling docs, check the catalog, then take the dojo.'

def mk_template(
    picked, # Native custom call/result pairs
    opening=OPENING, # Reply text preceding the first tool call
    closing="OK I'm ready.", # Reply text ending the round
    doced=None, # Names doc()'d during the round
):
    "A template dialog with native tool output left untruncated"
    items = [codex_msg('user',TMPL_PROMPT),codex_msg('assistant',opening),*picked,codex_msg('assistant',closing)]
    dlg = items2dlg(items,'codexdojo_template',mx=None)
    dlg.meta['llmdojo'] = dict(doced=list(doced or []))
    return dlg

# %% ../nbs/01_codexdojo.ipynb #53296a0a
SAMPLE_POLICY = dict(user_toks=999999, asst_toks=999999, call_toks=999999, result_toks=999999)
_SAMPLE_SKIP = ('dojo_start()', 'dojo_score(', '# kata', '%cd ')

def dojo_sample(src):
    "The completed dojo's substantive calls rendered as a compact sample session"
    pairs,out = dojo_round(src),[]
    for call,result in zip(pairs[::2],pairs[1::2]):
        if not _cell(call).lstrip().startswith(_SAMPLE_SKIP): out += [call,result]
    return compact_chat(items2chat(out), **SAMPLE_POLICY)

# %% ../nbs/01_codexdojo.ipynb #540516dd
TMPL_DIR = files('llmdojo')/'dojo_data'/'codex_store'   # package data: compiled by dojobuild, shipped with the code

# %% ../nbs/01_codexdojo.ipynb #2b6684cd
def save_template(
    items, # Curated native template items
    d=None, # Store dir; `TMPL_DIR` if None
    doced=None, # Names doc()'d during the baked round; current doc-state if None
):
    "Write the template and its metadata to the store"
    save_store(Path(d or TMPL_DIR), items, dojo_cid(items), doced)

# %% ../nbs/01_codexdojo.ipynb #80892363
def load_template(
    d=None, # Store dir; `TMPL_DIR` if None
):
    "The stored native items and metadata"
    return load_store(Path(d or TMPL_DIR))

# %% ../nbs/01_codexdojo.ipynb #635dbdd7
def build_template(
    src, # Path to a template dialog
    d=None, # Store dir; `TMPL_DIR` if None
):
    "Convert a reviewed template dialog back into the native store"
    dlg = read_ipynb(str(src))
    items = reid_items(dlg2items(dlg),'codexdojo')
    save_template(items,d,doced=nested_idx(dlg.meta,'llmdojo','doced') or [])

# %% ../nbs/01_codexdojo.ipynb #c51d054b
def _load_reg(d):
    "The loaded packaged store, registered, via the shared `load_reg`"
    return load_reg(d, TMPL_DIR, 'codexdojo')

# %% ../nbs/01_codexdojo.ipynb #f1c3a7b5
async def prep_dojo(
    cwd=None, # Project to start in; current directory if None
    d=None, # Template store dir; `TMPL_DIR` if None
    codex_home=None, # Alternate Codex home, primarily for tests
):
    "Create a thread containing the template and return its id"
    items,meta = _load_reg(d)
    async with codex_client(codex_home) as codex: thread = await codex.create_thread(reid_items(items,'launch:'+uuid.uuid4().hex),cwd=cwd)
    if ds:=meta.get('doced'): _seed_doced(thread.id,ds)
    return thread.id

# %% ../nbs/01_codexdojo.ipynb #6bdbb30e
def _prompt_text(item,text):
    item = obj2dict(item)
    item['content'] = [dict(type='input_text',text=text)]
    return item

async def append_dojo(
    sid=None, # Thread id to append to; newest thread for the project if None
    cwd=None, # Project directory; current directory if None
    d=None, # Template store dir; `TMPL_DIR` if None
    codex_home=None, # Alternate Codex home
):
    "Append the template to an existing thread and return its id"
    items,meta = _load_reg(d)
    sid,path = resolve_thread(sid,codex_home or CODEX_HOME) if sid else project_thread(cwd or '.',codex_home or CODEX_HOME)
    tail = load_recs(path)
    items = reid_items(items,f'append:{sid}:{len(tail)}')
    items[0] = _prompt_text(items[0],APPEND_PROMPT)
    async with codex_client(codex_home) as codex: await codex.append_thread(sid,items)
    _seed_doced(sid,meta.get('doced') or [],merge=True)
    return sid

# %% ../nbs/01_codexdojo.ipynb #c507e5da
def _is_prompt(x): return x.get('type')=='message' and x.get('role')=='user'

def _dealt(t): return any(re.match(_START_RE, _cell(x)) for x in t)

def strip_dojo(
    items, # Responses items in conversation order
):
    "Copy of `items` without the user turns that dealt a round (bare `dojo_start()`)"
    return _turns(items, _is_prompt).filter(_dealt, negate=True).concat()

def _strip(items):
    "`strip_dojo`, unless nothing else would remain to compact"
    s = strip_dojo(items)
    return s if items2chat(s) else items

# %% ../nbs/01_codexdojo.ipynb #3ca125e7
async def compact_dojo(
    sid=None, # Thread id to compact; newest thread for the project if None
    cwd=None, # Project directory; current directory if None
    d=None, # Template store dir; `TMPL_DIR` if None
    codex_home=None, # Alternate Codex home
):
    "Synthetically compact a thread with the compact DSL (previous dojo rounds removed first), then append the template round; returns its id"
    home = codex_home or CODEX_HOME
    sid,_ = resolve_thread(sid,home) if sid else project_thread(cwd or '.',home)
    compact_session(sid,home,strip=_strip)
    return await append_dojo(sid,cwd,d,codex_home)

# %% ../nbs/01_codexdojo.ipynb #7844e48b
@call_parse(nested=True, pos=['sess'])
def main(
    sess:str=None, # Thread id; the project's newest where omitted
    Resume:bool=False, # Append the round to an existing thread after compaction, then resume it
    Compact:bool=False, # Synthetically compact the thread with the compact DSL, then append the round and resume
    sid:bool=False, # Print the prepared thread id instead of launching codex
    capture:bool=False, # Run a clean round in a bare Codex child and store it
    current:bool=False, # Store the clean round an existing thread already played (`capture_current`)
):
    "Prepare a Codex thread opening with the worked round and launch `codex resume` on it; template maintenance is `dojobuild`"
    if capture: return capture_dojo()
    if current: return capture_current(sess)
    if Resume: s = asyncio.run(append_dojo(sess))
    elif Compact: s = asyncio.run(compact_dojo(sess))
    else:
        if sess: sys.exit(f"unexpected argument {sess!r}: a fresh launch takes no thread, and codex flag values need --flag=value form")
        s = asyncio.run(prep_dojo())
    if sid: return print(s)
    os.execvp('codex', ['codex', 'resume', s, *launch_config('codex'), *sys.argv[1:]])
