"""Pre-baked Codex sessions that demonstrate a clean llmdojo round

Docs: https://AnswerDotAI.github.io/llmdojo/codexdojo.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_codexdojo.ipynb.

# %% auto #0
__all__ = ['GATE_FORBID', 'TMPL_PROMPT', 'OPENING', 'TMPL_DIR', 'APPEND_PROMPT', 'USAGE', 'collapse_deferred', 'pick_calls',
           'pick_turns', 'dojo_round', 'curate_dojo', 'dojo_cid', 'is_clean', 'capture_current', 'mk_template',
           'save_template', 'load_template', 'build_template', 'prep_dojo', 'append_dojo', 'main']

# %% ../nbs/01_codexdojo.ipynb #db524999
import asyncio, json, os, re, sys, uuid
from importlib.resources import files
from fastcore.utils import *
from llmsurgery.oai import *
from llmsurgery.ipynb import read_ipynb, write_ipynb
from .rules import _state_root, doced

# %% ../nbs/01_codexdojo.ipynb #1f05a641
def _items(src):
    "Responses items from either rollout records or an item sequence"
    src = L(src)
    return response_items(src) if any(x.get('type')=='response_item' for x in src) else L(obj2dict(x) for x in src)

def _out_text(item):
    out = item.get('output','')
    if isinstance(out,str): return out
    return '\n'.join(x.get('text','') for x in out if x.get('type') in ('input_text','output_text'))

def _logical(item): return parse_exec(item.get('input','')) if item.get('type')=='custom_tool_call' else None

def _cell(item):
    p = _logical(item)
    src = p.arguments.get('chars','') if p and p.name=='tools.write_stdin' else ''
    if src.startswith('--\n'):
        lines = src.splitlines()
        if lines[-1].startswith('--'): src = '\n'.join(lines[1:-1])+'\n'
    return src

# %% ../nbs/01_codexdojo.ipynb #786bd5fb
def collapse_deferred(src):
    "Custom call/result pairs, replacing host-level deferred waits with their final result"
    items,out = _items(src),[]
    cis = [i for i,x in enumerate(items) if x.get('type')=='custom_tool_call']
    for n,i in enumerate(cis):
        call,end = items[i],cis[n+1] if n+1<len(cis) else len(items)
        seg = items[i+1:end]
        result = first(x for x in seg if x.get('type')=='custom_tool_call_output' and x.get('call_id')==call.get('call_id'))
        if not result: continue
        if 'Script running with cell ID' in _out_text(result):
            waits = [x for x in seg if x.get('type')=='function_call' and x.get('name')=='wait']
            if waits:
                final = first(x for x in seg if x.get('type')=='function_call_output' and x.get('call_id')==waits[-1].get('call_id'))
                if final: result = codex_custom_output(call['call_id'], final.get('output',''))
        out += [call,result]
    return L(out)

# %% ../nbs/01_codexdojo.ipynb #629226fd
def pick_calls(
    src, # Rollout records or Responses items
    *specs, # `(logical_name, cell_source_or_argument_subset)` pairs
):
    "The last matching custom call/result pair for each spec, in spec order"
    pairs = collapse_deferred(src)
    calls = [(pairs[i],pairs[i+1],_logical(pairs[i])) for i in range(0,len(pairs),2)]
    out = []
    for name,want in specs:
        cand = [(c,r,p) for c,r,p in calls if p and p.name==name]
        if isinstance(want,dict): cand = [(c,r,p) for c,r,p in cand if all(p.arguments.get(k)==v for k,v in want.items())]
        else:
            exact = [(c,r,p) for c,r,p in cand if p.arguments.get('chars','')==want]
            cand = exact or [(c,r,p) for c,r,p in cand if p.arguments.get('chars','').startswith(want)]
        if not cand: raise ValueError(f'no custom call matches {name} {want!r}')
        out += cand[-1][:2]
    return L(out)

# %% ../nbs/01_codexdojo.ipynb #9e66e463
def pick_turns(
    src, # Rollout records or Responses items
    *cells, # Kernel cell sources: matched exactly, else as a prefix; the last match wins
):
    "The write_stdin call/result pairs for `cells`, in that order"
    return pick_calls(src, *((('tools.write_stdin',c) for c in cells)))

# %% ../nbs/01_codexdojo.ipynb #2dbf7eb2
def dojo_round(src):
    "The last complete dojo_start()/dojo_score() custom-tool span"
    pairs = collapse_deferred(src)
    calls = pairs[::2]
    starts = [i for i,c in enumerate(calls) if re.match(r'^dojo_start\(\s*\)\s*$', _cell(c))]
    if not starts: raise ValueError('no dojo_start() call')
    start = starts[-1]
    scores = [i for i,c in enumerate(calls[start:],start) if re.match(r'^dojo_score\(', _cell(c))]
    if not scores: raise ValueError('no dojo_score() after dojo_start()')
    return pairs[start*2:(scores[0]+1)*2]

# %% ../nbs/01_codexdojo.ipynb #c4ac3c42
def curate_dojo(src):
    "The reproducible custom-tool items for the last complete dojo round"
    return reid_items(dojo_round(src), 'codexdojo')

# %% ../nbs/01_codexdojo.ipynb #705852d8
def dojo_cid(items):
    "The completion id recorded in the clean-round output"
    return first(m[1] for x in items if (m:=re.search(r'Completion id: ([0-9a-f]{4})', item_txt(x))))

# %% ../nbs/01_codexdojo.ipynb #ce3882cc
GATE_FORBID = ('recording a demo', 'these notes')

def is_clean(
    items, # A curated dojo round
    forbid=GATE_FORBID, # Phrases that must not appear in visible assistant text
):
    "Why a captured round cannot become a template; empty means clean"
    items = _items(items)
    calls = [x for x in items if x.get('type')=='custom_tool_call']
    cells = [_cell(x) for x in calls]
    probs = []
    if (n:=sum(bool(re.match(r'^dojo_start\(\s*\)\s*$', c)) for c in cells)) != 1: probs.append(f'{n} dojo_start calls')
    if (n:=sum(bool(re.match(r'^dojo_score\(', c)) for c in cells)) != 1: probs.append(f'{n} dojo_score calls (a clean round scores once, first try)')
    if any(re.match(r'^dojo_(?:redo|resume)\(', c) for c in cells): probs.append('needed a redo')
    if not any('Clean round' in _out_text(x) for x in items if x.get('type')=='custom_tool_call_output'): probs.append('no clean score')
    if (n:=sum('\nTraceback (most recent call last):' in _out_text(x) for x in items if x.get('type')=='custom_tool_call_output')): probs.append(f'{n} failed tool calls')
    ids = {x.get('call_id') for x in items if x.get('type')=='custom_tool_call_output'}
    if (n:=sum(x.get('call_id') not in ids for x in calls)): probs.append(f'{n} calls without results')
    visible = ' '.join(item_txt(x) for x in items if x.get('type')=='message' and x.get('role')=='assistant')
    if (bad:=[s for s in forbid if s in visible]): probs.append(f"script leaked into visible text: {', '.join(bad)}")
    return probs

# %% ../nbs/01_codexdojo.ipynb #fce1bcb2
def _capture_span(src):
    "Native custom-call pairs from the last clikernel launch through its first dojo score"
    pairs = collapse_deferred(src)
    calls,cells = pairs[::2],[_cell(x) for x in pairs[::2]]
    starts = [i for i,c in enumerate(cells) if re.match(r'^dojo_start\(\s*\)\s*$',c)]
    if not starts: raise ValueError('no dojo_start() call')
    start = starts[-1]
    scores = [i for i,c in enumerate(cells[start:],start) if re.match(r'^dojo_score\(',c)]
    if not scores: raise ValueError('no dojo_score() after dojo_start()')
    launches = [i for i,c in enumerate(calls[:start+1]) if (p:=_logical(c)) and p.name=='tools.exec_command' and p.arguments.get('cmd')=='clikernel']
    if not launches: raise ValueError('no clikernel launch before dojo_start()')
    return pairs[launches[-1]*2:(scores[0]+1)*2]

def capture_current(
    ref=None, # Codex thread UUID; current thread if None
    d=None, # Template store dir; `TMPL_DIR` if None
    docs=None, # Names doc()'d in the captured thread; current doc-state if None
):
    "Gate an existing Codex thread's clean round and store its native template"
    selected = reid_items(_capture_span(response_items(load_rollout(ref))),'codexdojo')
    if probs:=is_clean(selected): raise ValueError('; '.join(probs))
    docs = doced() if docs is None else docs
    dlg = mk_template(selected,doced=docs)
    save_template(dlg2items(dlg),d,doced=docs)
    write_ipynb(dlg,Path(d or TMPL_DIR)/'template.ipynb')
    return dlg

# %% ../nbs/01_codexdojo.ipynb #8c6b39a0
TMPL_PROMPT = "Bootstrap and complete the dojo and tell me when you're ready."
OPENING = 'Bootstrapping: I launch clikernel, read the tooling docs, check the catalog, then take the dojo.'

def mk_template(
    picked, # Native custom call/result pairs
    opening=OPENING, # Reply text preceding the first tool call
    closing="OK I'm ready.", # Reply text ending the round
    doced=None, # Names doc()'d during the round
):
    "A template dialog with native tool output left untruncated"
    items = [codex_msg('user',TMPL_PROMPT),codex_msg('assistant',opening),*picked,codex_msg('assistant',closing)]
    dlg = items2dlg(items,'codexdojo_template',mx=None)
    dlg.meta['llmdojo'] = dict(doced=list(doced or []))
    return dlg

# %% ../nbs/01_codexdojo.ipynb #540516dd
TMPL_DIR = _state_root()/'codex_template'

def _dojo_v():
    from llmdojo.dojo import dojo_version
    return dojo_version()

# %% ../nbs/01_codexdojo.ipynb #2b6684cd
def save_template(
    items, # Curated native template items
    d=None, # Store dir; `TMPL_DIR` if None
    doced=None, # Names doc()'d during the baked round; current doc-state if None
):
    "Write the template and its metadata to the store"
    if doced is None:
        from llmdojo.rules import doced as _cur
        doced = _cur()
    d = Path(d or TMPL_DIR)
    d.mkdir(parents=True,exist_ok=True)
    (d/'template.jsonl').write_text(''.join(json.dumps(obj2dict(x))+'\n' for x in items))
    (d/'meta.json').write_text(json.dumps(dict(cid=dojo_cid(items),v=_dojo_v(),doced=list(doced))))

# %% ../nbs/01_codexdojo.ipynb #80892363
def load_template(
    d=None, # Store dir; `TMPL_DIR` if None
):
    "The stored native items and metadata"
    d = Path(d or TMPL_DIR)
    return [json.loads(x) for x in (d/'template.jsonl').read_text().splitlines()],json.loads((d/'meta.json').read_text())

# %% ../nbs/01_codexdojo.ipynb #635dbdd7
def build_template(
    src, # Path to a template dialog
    d=None, # Store dir; `TMPL_DIR` if None
):
    "Convert a reviewed template dialog back into the native store"
    dlg = read_ipynb(str(src))
    items = reid_items(dlg2items(dlg),'codexdojo')
    save_template(items,d,doced=nested_idx(dlg.meta,'llmdojo','doced') or [])

# %% ../nbs/01_codexdojo.ipynb #c51d054b
def _load_reg(d):
    "Load the store, building it from the packaged dialog on first use"
    if not (Path(d or TMPL_DIR)/'template.jsonl').exists(): build_template(files('llmdojo')/'dojo_data'/'codexdojo_template.ipynb',d)
    items,meta = load_template(d)
    if meta['v'] != _dojo_v(): print(f"codexdojo: template built under {meta['v']} but installed tooling is {_dojo_v()}; rebuild the reviewed dialog with codexdojo --build <dialog>.")
    from llmdojo.dojo import register_completion
    register_completion(meta['cid'],meta['v'])
    return items,meta

def _seed_doced(sid,names,merge=False):
    "Make the baked round's documented-tool state true for thread `sid`"
    d = _state_root()/'doced'
    d.mkdir(parents=True,exist_ok=True)
    f = d/f'{sid}.json'
    if merge and f.exists(): names = set(names) | set(json.loads(f.read_text()))
    f.write_text(json.dumps(sorted(names)))

# %% ../nbs/01_codexdojo.ipynb #f1c3a7b5
async def prep_dojo(
    cwd=None, # Project to start in; current directory if None
    d=None, # Template store dir; `TMPL_DIR` if None
    codex_home=None, # Alternate Codex home, primarily for tests
):
    "Create a thread containing the template and return its id"
    items,meta = _load_reg(d)
    async with CodexAppServer(codex_home=codex_home) as app:
        thread = await app.create_thread(reid_items(items,'launch:'+uuid.uuid4().hex),cwd=cwd)
    if ds:=meta.get('doced'): _seed_doced(thread.id,ds)
    return thread.id

# %% ../nbs/01_codexdojo.ipynb #6bdbb30e
APPEND_PROMPT = "We've compacted - run the dojo round again and tell me when you're ready."

def _prompt_text(item,text):
    item = obj2dict(item)
    item['content'] = [dict(type='input_text',text=text)]
    return item

async def append_dojo(
    sid=None, # Thread id to append to; newest thread for the project if None
    cwd=None, # Project directory; current directory if None
    d=None, # Template store dir; `TMPL_DIR` if None
    codex_home=None, # Alternate Codex home
):
    "Append the template to an existing thread and return its id"
    items,meta = _load_reg(d)
    sid,path = resolve_thread(sid,codex_home or CODEX_HOME) if sid else project_thread(cwd or '.',codex_home or CODEX_HOME)
    tail = load_recs(path)
    items = reid_items(items,f'append:{sid}:{len(tail)}')
    items[0] = _prompt_text(items[0],APPEND_PROMPT)
    async with CodexAppServer(codex_home=codex_home) as app: await app.append_thread(sid,items)
    _seed_doced(sid,meta.get('doced') or [],merge=True)
    return sid

# %% ../nbs/01_codexdojo.ipynb #7844e48b
USAGE = """usage: codexdojo [--build <dialog.ipynb> | --capture-current [thread-id] | --sid | -r [thread-id] | <codex args...>]
Start Codex in the current project with a completed dojo round already in its session history.
  --build <dialog.ipynb>       convert a reviewed template dialog and store it
  --capture-current [thread]   curate an existing thread's clean round and store it
  --sid                        prepare and print a thread id instead of launching
  -r [thread-id]               append the round to an existing thread after compaction
  <codex args...>              anything else is passed through to `codex resume`"""

def main():
    "CLI entry point; run `codexdojo -h` for usage"
    args = sys.argv[1:]
    if args[:1] in (['-h'],['--help']) or (args[:1]==['--build'] and len(args)!=2) \
        or (args[:1]==['--capture-current'] and len(args)>2) \
        or (args[:1]==['-r'] and len(args)>2): return print(USAGE)
    if args[:1]==['--build']: return build_template(args[1])
    if args[:1]==['--capture-current']:
        capture_current(args[1] if len(args)==2 else None)
        return
    if args[:1]==['-r']: return print(asyncio.run(append_dojo(args[1] if len(args)==2 else None)))
    if args==['--sid']: return print(asyncio.run(prep_dojo()))
    os.execvp('codex',['codex','resume',asyncio.run(prep_dojo()),*args])
