"""Start ipyai with a worked tooling session already in its history

An ipyai session is an aidialog `Dialog`, saved whole as an `.ipynb` under `./.ipyai/sessions/`, and ipyai rebuilds the model's context from that dialog on every turn (`dlg2hist`). So the template needs no host-native record format: the canonical dojo dialog already has the shape ipyai resumes. What differs from the clikernel hosts is the tool. ipyai's model runs code through `py`, which runs the cell in the user's kernel and renders its outputs with aidialog's `render_outputs_ai`, so the baked round must show `py` calls with `py` results. `ipyaidojo` gets them by replaying the canonical round's cells through ipyai's own kernel client, with no model spend, and with the first bootstrap read swapped: ipyai has no `clik` skill to document. Launch is then a session write plus `ipyai -r`.

Docs: https://AnswerDotAI.github.io/llmdojo/ipyaidojo.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_ipyaidojo.ipynb.

# %% auto #0
__all__ = ['TOOL', 'BOOT_CLIK', 'BOOT', 'TMPL_DIR', 'ipyai_cells', 'replay_cells', 'ipyai_dialog', 'build_template',
           'load_template', 'template_dialog', 'prep_dojo', 'main']

# %% ../nbs/03_ipyaidojo.ipynb #43a45dc9
import json, os, sys, tempfile
from importlib.resources import files
from fastcore.utils import *
from fastcore.script import call_parse
from aidialog.ipynb import read_ipynb, write_ipynb, reads_ipynb
from aidialog.hist import reply2dlg, dlg2reply, _parse_call
from aidialog.dialog import code_output, prompt_output
from aidialog.msg_parts import ToolResponse, tool_text
from .tmpl import save_store, load_store, load_reg, round_gates, find_cid, doced_names, launch_config, DOJO_CANON, _seed_doced

# %% ../nbs/03_ipyaidojo.ipynb #e82c3701
TOOL = 'py'   # ipyai's model-facing tool: runs a cell in the user's kernel
BOOT_CLIK, BOOT = 'doc(clik, pysk, edsk)', 'doc(pysk, edsk)'

def ipyai_cells(
    cells, # The canonical round's kernel cell sources
):
    "The same round as ipyai plays it: the clikernel bootstrap read becomes the shared pair, since ipyai has no `clik`"
    return [BOOT if c.strip()==BOOT_CLIK else c for c in cells]

# %% ../nbs/03_ipyaidojo.ipynb #3182e33a
async def replay_cells(
    cells, # Kernel cell sources, run in order
    cwd, # Directory to start the kernel in
    env=None, # Extra environment entries for the kernel process
):
    "Each cell's `py` result from a fresh ipyai kernel at `cwd`: the text the model reads in a live session"
    from ipyai.kernel import KernelSession
    from ipyai.bridge import setup_tools
    k = await KernelSession().start(cwd=cwd, env=env)
    try:
        _,tools = await setup_tools(k.kc)
        outs = []
        for c in cells:
            r = await tools.call_text(TOOL, dict(code=c))
            outs.append(tool_text(r.content if isinstance(r, ToolResponse) else r))
        return outs
    finally: await k.close()

# %% ../nbs/03_ipyaidojo.ipynb #625f120b
TMPL_DIR = files('llmdojo')/'dojo_data'/'ipyai_store'   # package data: compiled by dojobuild, shipped with the code

async def ipyai_dialog(
    src, # Path to the canonical template dialog .ipynb
    cwd, # Directory to replay in
):
    "The canonical round as ipyai plays it: calls renamed to `py`, results regenerated by replay, gated, canonicalized; returns `(dialog, outs)`"
    from llmdojo.dojo import _run_dir
    dlg = read_ipynb(str(src))
    pmsg = dlg.messages[0]
    sub = reply2dlg(pmsg)
    codes = [m for m in sub.messages if m.msg_type=='code']
    cells = ipyai_cells([_parse_call(m.content)[1]['code'].replace(DOJO_CANON, str(_run_dir())) for m in codes])   # localize: the round plays in the real run dir
    outs = await replay_cells(cells, cwd)
    for m,c,o in zip(codes, cells, outs): m.content,m.output = f'{TOOL}(code={c!r})',code_output(o)
    if probs := round_gates(cells, outs, ' '.join(m.content for m in sub.messages if m.msg_type=='note')): raise ValueError('; '.join(probs))
    pmsg.output = prompt_output(dlg2reply(sub).replace(str(_run_dir()), DOJO_CANON))   # canonicalize: the stored artifact reads the same everywhere
    dlg.meta['llmdojo'] = dict(doced=doced_names(cells))
    return dlg,outs

async def build_template(
    src, # Path to the canonical template dialog .ipynb
    d=None, # Store dir; `TMPL_DIR` if None
):
    "Replay the canonical dialog through ipyai and write the ipyai store: the dialog as a notebook dict, its completion id, and its doced list"
    with tempfile.TemporaryDirectory(prefix='ipyaidojo_') as td: dlg,outs = await ipyai_dialog(src, td)
    save_store(Path(d or TMPL_DIR), [json.loads(write_ipynb(dlg))], find_cid(outs), doced=dlg.meta['llmdojo']['doced'])
    return dlg

def load_template(
    d=None, # Store dir; `TMPL_DIR` if None
):
    "The stored template items and metadata"
    return load_store(Path(d or TMPL_DIR))

def template_dialog(
    items, # Stored template items: one notebook dict
):
    "The template dialog read back from its stored notebook dict"
    return reads_ipynb(json.dumps(items[0]))

# %% ../nbs/03_ipyaidojo.ipynb #b83fc9a2
def prep_dojo(
    cwd=None, # Project to start in; the current directory if None
    d=None, # Template store dir; `TMPL_DIR` if None
):
    "Write the template as a session of `cwd` through ipyai's `Session`, register its completion id, seed its doc-state, and return the session id to resume"
    from ipyai.session import Session
    items,meta = load_reg(d, TMPL_DIR, 'ipyaidojo')
    s = Session(root=cwd or '.')
    s.save(template_dialog(items))
    if ds := meta.get('doced'): _seed_doced(s.path.stem, ds)   # ipyai names the session stem in the kernel's LLMDOJO_HOST_ID
    return s.path.stem

# %% ../nbs/03_ipyaidojo.ipynb #2ab65f78
@call_parse(nested=True)
def main(
    sid:bool=False, # Print the prepared session id instead of launching ipyai
):
    "Prepare an ipyai session opening with the worked round and launch `ipyai -r` on it; template maintenance is `dojobuild`"
    s = prep_dojo()
    if sid: return print(s)
    os.execvp('ipyai', ['ipyai', *launch_config('ipyai'), '-r', s, *sys.argv[1:]])
