"""Start ipyai with a worked tooling session already in its history

An ipyai session is an aidialog `Dialog`, saved whole as an `.ipynb` under `./.ipyai/sessions/`, and ipyai rebuilds the model's context from that dialog on every turn (`dlg2hist`). So the template needs no host-native record format: the packaged dialogs already have the shape ipyai resumes. What differs from the clikernel hosts is the tool and the bootstrap. ipyai's model runs code through `py`, which runs the cell in the user's kernel and renders its outputs with the same `render_text` clikernel uses, so the baked round must show `py` calls; `ipyaidojo` gets them by replaying the cells through ipyai's own kernel client, with no model spend. And ipyai has no `clik` skill to document, so its bootstrap is its own dialog, captured from an ipyai session, assembled with the shared round at build time. Launch is then a session write plus `ipyai -r`.

Docs: https://AnswerDotAI.github.io/llmdojo/ipyaidojo.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_ipyaidojo.ipynb.

# %% auto #0
__all__ = ['TOOL', 'BOOT_PATH', 'BOOT_PROMPT', 'TMPL_DIR', 'replay_cells', 'ipyai_dialog', 'build_template', 'load_template',
           'template_dialog', 'capture_boot', 'prep_dojo', 'main']

# %% ../nbs/03_ipyaidojo.ipynb #43a45dc9
import asyncio, json, os, sys, tempfile
from importlib.resources import files
from fastcore.utils import *
from fastcore.script import call_parse
from aidialog.ipynb import read_ipynb, write_ipynb, reads_ipynb
from aidialog.msg_parts import ToolResponse, tool_text
from .tmpl import save_store, load_store, load_reg, find_cid, launch_config, assemble, localized_cells, refresh_dialog, boot_gates
from .tmpl import _seed_doced, _pmsgs, _msg_cells, _one_prompt

# %% ../nbs/03_ipyaidojo.ipynb #e82c3701
TOOL = 'py'   # ipyai's model-facing tool: runs a cell in the user's kernel
BOOT_PATH = files('llmdojo')/'dojo_data'/'ipyai_boot.ipynb'   # ipyai's bootstrap: one prompt, its reply the startup's doc() reads through `py`
BOOT_PROMPT = "Bootstrap with py, one call each: doc(pysk, edsk), then doc(dsk, exh, rgsk), then doc(acp), then list_pyskills(). Then tell me when you're ready."

# %% ../nbs/03_ipyaidojo.ipynb #3182e33a
async def replay_cells(
    cells, # Kernel cell sources, run in order
    cwd, # Directory to start the kernel in
    env=None, # Extra environment entries for the kernel process
):
    "Each cell's `py` result from a fresh ipyai kernel at `cwd`: the text the model reads in a live session"
    from ipyai.kernel import KernelSession
    from ipyai.bridge import setup_tools
    k = await KernelSession().start(cwd=cwd, env=env)
    try:
        _,tools = await setup_tools(k.kc)
        outs = []
        for c in cells:
            r = await tools.call_text(TOOL, dict(code=c))
            outs.append(tool_text(r.content if isinstance(r, ToolResponse) else r))
        return outs
    finally: await k.close()

# %% ../nbs/03_ipyaidojo.ipynb #625f120b
TMPL_DIR = files('llmdojo')/'dojo_data'/'ipyai_store'   # package data: compiled by dojobuild, shipped with the code

async def ipyai_dialog(
    boot=None, # ipyai's bootstrap dialog (or its path); the packaged one if None
    rnd=None, # The round dialog (or its path); the packaged round if None
    cwd=None, # Directory to replay in; the current directory if None
):
    "The template as ipyai plays it: its bootstrap and the shared round, calls renamed to `py`, results regenerated by replay, gated, canonicalized; returns `(dialog, outs)`"
    dlg = assemble(boot or BOOT_PATH, rnd)
    outs = [await replay_cells(cells, cwd or '.') for cells in localized_cells(dlg)]
    return refresh_dialog(dlg, outs, tool=TOOL), outs

async def build_template(
    boot=None, # ipyai's bootstrap dialog (or its path); the packaged one if None
    rnd=None, # The round dialog (or its path); the packaged round if None
    d=None, # Store dir; `TMPL_DIR` if None
):
    "Replay the template through ipyai and write the ipyai store: the dialog as a notebook dict, its completion id, and its doced list"
    with tempfile.TemporaryDirectory(prefix='ipyaidojo_') as td: dlg,outs = await ipyai_dialog(boot, rnd, td)
    save_store(Path(d or TMPL_DIR), [json.loads(write_ipynb(dlg))], find_cid(L(outs).concat()), doced=dlg.meta['llmdojo']['doced'])
    return dlg

def load_template(
    d=None, # Store dir; `TMPL_DIR` if None
):
    "The stored template items and metadata"
    return load_store(Path(d or TMPL_DIR))

def template_dialog(
    items, # Stored template items: one notebook dict
):
    "The template dialog read back from its stored notebook dict"
    return reads_ipynb(json.dumps(items[0]))

# %% ../nbs/03_ipyaidojo.ipynb #9d2a7f80
async def capture_boot(
    sess=None, # An ipyai session id or name prefix; the project's newest session if None
    cwd=None, # Project directory; the current directory if None
    d=None, # Template store dir; `TMPL_DIR` if None
):
    "ipyai's bootstrap from a session that answered `BOOT_PROMPT`: the last prompt whose reply is nothing but doc reads, replayed for full results, written to `boot.ipynb` beside the store"
    from ipyai.session import resolve_session, list_sessions
    path = resolve_session(sess, cwd or '.') if sess else list_sessions(cwd or '.')[0][0]
    dlg = read_ipynb(str(path))
    pm = last(m for m in _pmsgs(dlg) if not boot_gates(_msg_cells(m)[2]))
    if pm is None: raise ValueError(f'no bootstrap reply (a prompt answered only with doc reads) in {path}')
    b = _one_prompt(pm, 'ipyai_boot')
    b.messages[0].content = BOOT_PROMPT
    with tempfile.TemporaryDirectory(prefix='ipyaidojo_') as td: outs = [await replay_cells(cells, td) for cells in localized_cells(b)]
    refresh_dialog(b, outs, tool=TOOL)   # the session file stores tool results truncated; the replay restores the full text the model read
    out = Path(d or TMPL_DIR)/'boot.ipynb'
    write_ipynb(b, str(out))
    return out

# %% ../nbs/03_ipyaidojo.ipynb #b83fc9a2
def prep_dojo(
    cwd=None, # Project to start in; the current directory if None
    d=None, # Template store dir; `TMPL_DIR` if None
):
    "Write the template as a session of `cwd` through ipyai's `Session`, register its completion id, seed its doc-state, and return the session id to resume"
    from ipyai.session import Session
    items,meta = load_reg(d, TMPL_DIR, 'ipyaidojo')
    s = Session(root=cwd or '.')
    s.save(template_dialog(items))
    if ds := meta.get('doced'): _seed_doced(s.path.stem, ds)   # ipyai names the session stem in the kernel's LLMDOJO_HOST_ID
    return s.path.stem

# %% ../nbs/03_ipyaidojo.ipynb #2ab65f78
@call_parse(nested=True)
def main(
    sid:bool=False, # Print the prepared session id instead of launching ipyai
    capture:bool=False, # Capture ipyai's bootstrap from this project's newest session into the store's `boot.ipynb`, and exit
):
    "Prepare an ipyai session opening with the worked round and launch `ipyai -r` on it; template maintenance is `dojobuild`"
    if capture: return print(f"wrote: {asyncio.run(capture_boot())}")
    s = prep_dojo()
    if sid: return print(s)
    os.execvp('ipyai', ['ipyai', *launch_config('ipyai'), '-r', s, *sys.argv[1:]])
