"""The template layer shared by claudedojo and codexdojo

The claudedojo and codexdojo launchers are mirror images: each captures a clean dojo round, gates it, stores it beside its metadata, and splices it into sessions at launch time. They differ only in the record shape their host uses (Claude Code transcript records vs Codex Responses items) and in transport. Everything representation-independent lives here instead of twice over there: the shared prompts and gate phrases, the completion-id receipt, the store layout, the launch-time loader and doc-state seeding, the content gates, and the round's structural boundaries. A backend contributes only its extractors, its transport, and its capture child.

Docs: https://AnswerDotAI.github.io/llmdojo/tmpl.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_tmpl.ipynb.

# %% auto #0
__all__ = ['TMPL_PROMPT', 'APPEND_PROMPT', 'GATE_FORBID', 'CAPTURE_SCRIPT', 'DOJO_CANON', 'find_cid', 'save_store', 'load_store',
           'load_reg', 'round_gates', 'capture_slice', 'doced_names', 'canon_tmpl', 'refresh_template', 'main']

# %% ../nbs/02_tmpl.ipynb #5d058b1b
import json, os, re, subprocess, sys, tempfile
from importlib.resources import files
from fastcore.utils import *
from fastcore.script import call_parse
from clikernel.base import _MARKER as _CLIK_MARKER
from aidialog.ipynb import read_ipynb, write_ipynb
from aidialog.hist import reply2dlg, dlg2reply, _parse_call
from aidialog.dialog import code_output, prompt_output
from .rules import _state_root, _docnames

# %% ../nbs/02_tmpl.ipynb #159f53fb
TMPL_PROMPT = "Bootstrap and complete the dojo and tell me when you're ready."
APPEND_PROMPT = "We've compacted - run the dojo round again and tell me when you're ready."
GATE_FORBID = ('recording a demo', 'these notes')
CAPTURE_SCRIPT = (files('llmdojo')/'dojo_data'/'capture_prompt.md').read_text()

# %% ../nbs/02_tmpl.ipynb #e01183e6
def find_cid(
    txts, # Record texts, in order
):
    "The completion id receipt in a clean round's texts"
    return first(m[1] for t in txts if (m := re.search(r'Completion id: ([0-9a-f]{4})', t)))

def _dojo_v():
    from llmdojo.dojo import dojo_version
    return dojo_version()

# %% ../nbs/02_tmpl.ipynb #5e0ff173
def save_store(
    d, # Store dir
    items, # Native template items or records
    cid, # The round's completion id receipt
    doced=None, # Names doc()'d during the baked round; the current conversation's doc-state if None
):
    "Write a template and its metadata to the store at `d`"
    if doced is None:
        from llmdojo.rules import doced as _cur
        doced = _cur()
    d = Path(d)
    d.mkdir(parents=True, exist_ok=True)
    (d/'template.jsonl').write_text(''.join(json.dumps(obj2dict(x))+'\n' for x in items))
    (d/'meta.json').write_text(json.dumps(dict(cid=cid, v=_dojo_v(), doced=list(doced))))

def load_store(
    d, # Store dir
):
    "The stored native items and metadata at `d`"
    d = Path(d)
    return (d/'template.jsonl').read_jsonl(), json.loads((d/'meta.json').read_text())

# %% ../nbs/02_tmpl.ipynb #f0e81e3c
def load_reg(
    d, # Store dir; `default` if None
    default, # The backend's default store dir
    pkg, # The packaged fallback dialog's filename in `dojo_data`
    build, # The backend's dialog-to-store converter, e.g. its `build_template`
    prog, # The backend's program name, for the skew warning
):
    "Load a template store (built from the packaged dialog if empty), warn on version skew, and register its completion id"
    d = Path(d or default)
    if not (d/'template.jsonl').exists(): build(files('llmdojo')/'dojo_data'/pkg, d)
    items,meta = load_store(d)
    if meta['v'] != _dojo_v(): print(f"{prog}: template built under {meta['v']} but installed tooling is {_dojo_v()}; the baked round will not validate. Rebuild with dojobuild, or recapture with {prog} --capture.", file=sys.stderr)
    from llmdojo.dojo import register_completion
    register_completion(meta['cid'], meta['v'])
    return items,meta

# %% ../nbs/02_tmpl.ipynb #6de89054
def _seed_doced(sid, names, merge=False):
    "Make the baked round's doc-state true for conversation `sid`"
    d = _state_root()/'doced'
    d.mkdir(parents=True, exist_ok=True)
    f = d/f'{sid}.json'
    if merge and f.exists(): names = set(names) | set(json.loads(f.read_text()))
    f.write_text(json.dumps(sorted(names)))

# %% ../nbs/02_tmpl.ipynb #d4559c82
_START_RE = r'^dojo_start\(\s*\)\s*$'

def round_gates(
    cells, # The round's kernel cell sources, in order
    outs, # Its tool output texts
    visible, # Its visible assistant text, joined
    forbid=GATE_FORBID, # Phrases that must not appear in visible text
):
    "The content problems that disqualify a round from becoming a template, whichever host played it"
    probs = []
    if (n := sum(bool(re.match(_START_RE, c)) for c in cells)) != 1: probs.append(f'{n} dojo_start calls')
    if (n := sum(bool(re.match(r'^dojo_score\(', c)) for c in cells)) != 1: probs.append(f'{n} dojo_score calls (a clean round scores once, first try)')
    if any(re.match(r'^dojo_(?:redo|resume)\(', c) for c in cells): probs.append('needed a redo')
    if not any('Clean round' in o for o in outs): probs.append('no clean score')
    if (bad := [f for f in forbid if f in visible]): probs.append(f"script leaked into visible text: {', '.join(bad)}")
    return probs

# %% ../nbs/02_tmpl.ipynb #973e791f
def capture_slice(
    cells, # Kernel cell sources of a conversation's calls, in order
):
    "The `(first, last)` cell indices of the captured round: bootstrap docs through the first score of the last dealt round"
    starts = [i for i,c in enumerate(cells) if re.match(_START_RE, c)]
    if not starts: raise ValueError('no dojo_start() call')
    start = starts[-1]
    boots = [i for i,c in enumerate(cells[:start]) if re.match(r'^doc\(clik,\s*pysk,\s*edsk\)\s*$', c)]
    if not boots: raise ValueError('no bootstrap doc call before dojo_start()')
    scores = [i for i,c in enumerate(cells[start:], start) if re.match(r'^dojo_score\(', c)]
    if not scores: raise ValueError('no dojo_score() after dojo_start()')
    return boots[-1], scores[0]

# %% ../nbs/02_tmpl.ipynb #c5988523
def doced_names(
    cells, # Kernel cell sources
):
    "Names documented by standalone `doc(...)` calls in `cells`, in both spellings"
    docs = set()
    for c in cells:
        for m in re.finditer(r'(?m)^\s*doc\(([^()\n]+)\)\s*$', c):
            for name in m.group(1).split(','): docs.update(_docnames(name.strip()))
    return sorted(docs)

# %% ../nbs/02_tmpl.ipynb #0b76b9f7
def _replay_cells(
    cells, # Kernel cell sources, run in order
    cwd, # Directory to start the kernel in
    env=None, # Extra environment entries for the kernel process
):
    "Each cell's rendered response from a fresh `clikernel` CLI at `cwd`"
    p = subprocess.Popen(['clikernel'], cwd=str(cwd), env=os.environ|(env or {}), text=True,
        stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    def upto(stop):
        res = []
        for line in p.stdout:
            if (line := line.rstrip('\n')) == stop: return res
            res.append(line)
        raise RuntimeError(f'clikernel exited during replay; last lines: {res[-5:]}')
    upto(_CLIK_MARKER)
    delim = p.stdout.readline().rstrip('\n')
    outs = []
    for c in cells:
        p.stdin.write(f'--\n{c}\n{delim}\n')
        p.stdin.flush()
        if (ack := p.stdout.readline().rstrip('\n')) != '.': raise RuntimeError(f'expected ack, got {ack!r}')
        outs.append('\n'.join(upto(delim)))
    p.stdin.write('exit\n')
    p.stdin.flush()
    p.wait()
    return outs

# %% ../nbs/02_tmpl.ipynb #fe718d53
DOJO_CANON = '/tmp/dojo'

def canon_tmpl(
    dlg, # A template dialog whose reply holds a round
    canon=DOJO_CANON, # Canonical spelling for the round's run-dir path
):
    "Rewrite the round's run-dir path (read from its own `%cd` cell) to `canon` throughout the reply, so stored templates read the same on every machine"
    pm = dlg.messages[0]
    txt = pm.ai_res
    rd = first(re.findall(r"%cd ([^\s'\"\\]+)", txt))
    if rd and rd != canon: pm.output = prompt_output(txt.replace(rd, canon))
    return dlg

def refresh_template(
    src, # Path to a template dialog .ipynb
    dst=None, # Where to write the refreshed dialog; `src` if None
):
    "Replay `src`'s kernel cells through a fresh clikernel, splice in current outputs, refresh `doced`, and gate; writes and returns the refreshed (canonicalized) dialog"
    from llmdojo.dojo import _run_dir
    dlg = read_ipynb(str(src))
    pmsg = dlg.messages[0]
    sub = reply2dlg(pmsg)
    codes = [m for m in sub.messages if m.msg_type=='code']
    calls = [_parse_call(m.content) for m in codes]
    if bad := first(m.content for m,c in zip(codes,calls) if not (c and c[1].get('code'))): raise ValueError(f'not a kernel call: {bad}')
    cells = [c[1]['code'].replace(DOJO_CANON, str(_run_dir())) for c in calls]   # localize: the round plays in the real run dir
    with tempfile.TemporaryDirectory(prefix='dojorefresh_') as td:
        proj = Path(td)
        (proj/'pyproject.toml').write_text('[project]\nname = "dojo-refresh"\nversion = "0"\n')
        outs = _replay_cells(cells, proj)
    for m,(name,_),o in zip(codes, calls, outs): m.output = code_output(o or f'({name} completed with no output)')
    if probs := round_gates(cells, outs, ' '.join(m.content for m in sub.messages if m.msg_type=='note')): raise ValueError('; '.join(probs))
    pmsg.output = prompt_output(dlg2reply(sub).replace(str(_run_dir()), DOJO_CANON))   # canonicalize: the stored artifact reads the same everywhere
    dlg.meta['llmdojo'] = dict(doced=doced_names(cells))
    write_ipynb(dlg, str(dst or src))
    return dlg

# %% ../nbs/02_tmpl.ipynb #b31d935a
@call_parse(pos=['dialog'])
def main(
    dialog:str=None, # Template dialog path; the packaged dojo_data/dojo_template.ipynb where omitted
    claude:bool=False, # Build only the Claude store from the dialog, without refreshing
    codex:bool=False, # Build only the Codex store, without refreshing
):
    "Refresh the canonical template dialog (replaying its cells through a fresh clikernel), then build both stores"
    src = dialog or files('llmdojo')/'dojo_data'/'dojo_template.ipynb'
    from llmdojo import claudedojo, codexdojo
    if not (claude or codex):
        refresh_template(src)
        print(f'refreshed: {src}')
    if not codex:
        claudedojo.build_template(src)
        print(f'built: claude store ({claudedojo.TMPL_DIR})')
    if not claude:
        codexdojo.build_template(src)
        print(f'built: codex store ({codexdojo.TMPL_DIR})')
