"""The template layer shared by claudedojo and codexdojo

The claudedojo, codexdojo, and ipyaidojo launchers are mirror images: each gates a clean dojo round, stores it beside its metadata, and splices it into sessions at launch time. They differ only in the record shape their host uses (Claude Code transcript records, Codex Responses items, an ipyai session dialog), in transport, and in the bootstrap that opens the template - the host's own doc() reads, answered to the first of two prompts. Everything representation-independent lives here instead of three times over there: the shared prompts and gate phrases, the completion-id receipt, the store layout, the launch-time loader and doc-state seeding, the content gates, the captured dialog's structural boundaries, and the assembly of a host's bootstrap with the shared round. A backend contributes only its bootstrap dialog, its extractors, its transport, and its capture child.

Docs: https://AnswerDotAI.github.io/llmdojo/tmpl.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_tmpl.ipynb.

# %% auto #0
__all__ = ['BOOT_PROMPT', 'TMPL_PROMPT', 'APPEND_PROMPT', 'GATE_FORBID', 'CAPTURE_SCRIPT', 'ROUND_PATH', 'CLIK_BOOT',
           'DOJO_CANON', 'find_cid', 'save_store', 'load_store', 'load_reg', 'round_gates', 'capture_slice',
           'boot_gates', 'doced_names', 'template_cells', 'assemble', 'split_template', 'canon_tmpl', 'localized_cells',
           'refresh_dialog', 'refresh_template', 'launch_config', 'main']

# %% ../nbs/02_tmpl.ipynb #5d058b1b
import asyncio, json, os, re, subprocess, sys, tempfile, tomllib
from importlib.resources import files
from fastcore.utils import *
from fastcore.script import call_parse
from clikernel.cli import _MARKER as _CLIK_MARKER
from aidialog.ipynb import read_ipynb, write_ipynb
from aidialog.hist import reply2dlg, dlg2reply, _parse_call
from aidialog.dialog import Dialog, code_output, prompt_output
from .rules import _state_root, _docnames

# %% ../nbs/02_tmpl.ipynb #159f53fb
BOOT_PROMPT = "Bootstrap and tell me when you're ready."
TMPL_PROMPT = "Complete the dojo and tell me when you're ready."
APPEND_PROMPT = "We've compacted - bootstrap again and tell me when you're ready."
GATE_FORBID = ('recording a demo', 'these notes')
CAPTURE_SCRIPT = (files('llmdojo')/'dojo_data'/'capture_prompt.md').read_text()
ROUND_PATH = files('llmdojo')/'dojo_data'/'dojo_round.ipynb'   # the shared round: one prompt, its reply the worked dojo
CLIK_BOOT = files('llmdojo')/'dojo_data'/'clik_boot.ipynb'     # the clikernel hosts' bootstrap: one prompt, its reply the startup's doc() reads

# %% ../nbs/02_tmpl.ipynb #e01183e6
def find_cid(
    txts, # Record texts, in order
):
    "The completion id receipt in a clean round's texts"
    return first(m[1] for t in txts if (m := re.search(r'Completion id: ([0-9a-f]{4})', t)))

def _dojo_v():
    from llmdojo.dojo import dojo_version
    return dojo_version()

# %% ../nbs/02_tmpl.ipynb #5e0ff173
def save_store(
    d, # Store dir
    items, # Native template items or records
    cid, # The round's completion id receipt
    doced=None, # Names doc()'d during the baked round; the current conversation's doc-state if None
):
    "Write a template and its metadata to the store at `d`"
    if doced is None:
        from llmdojo.rules import doced as _cur
        doced = _cur()
    d = Path(d)
    d.mkdir(parents=True, exist_ok=True)
    (d/'template.jsonl').write_text(''.join(json.dumps(obj2dict(x))+'\n' for x in items))
    (d/'meta.json').write_text(json.dumps(dict(cid=cid, v=_dojo_v(), doced=list(doced))))

def load_store(
    d, # Store dir
):
    "The stored native items and metadata at `d`"
    d = Path(d)
    return (d/'template.jsonl').read_jsonl(), json.loads((d/'meta.json').read_text())

# %% ../nbs/02_tmpl.ipynb #f0e81e3c
def load_reg(
    d, # Store dir; `default` if None
    default, # The backend's packaged store dir
    prog, # The backend's program name, for the skew warning
):
    "Load a template store, warn on version skew, and register its completion id"
    items,meta = load_store(Path(d or default))
    if meta['v'] != _dojo_v(): print(f"{prog}: template built under {meta['v']} but installed tooling is {_dojo_v()}; the baked round will not validate. Rebuild with dojobuild.", file=sys.stderr)
    from llmdojo.dojo import register_completion
    register_completion(meta['cid'], meta['v'])
    return items,meta

# %% ../nbs/02_tmpl.ipynb #6de89054
def _seed_doced(sid, names, merge=False):
    "Make the baked round's doc-state true for conversation `sid`"
    d = _state_root()/'doced'
    d.mkdir(parents=True, exist_ok=True)
    f = d/f'{sid}.json'
    if merge and f.exists(): names = set(names) | set(json.loads(f.read_text()))
    f.write_text(json.dumps(sorted(names)))

# %% ../nbs/02_tmpl.ipynb #d4559c82
_START_RE = r'^dojo_start\(\s*\)\s*$'

def round_gates(
    cells, # The round's kernel cell sources, in order
    outs, # Its tool output texts
    visible, # Its visible assistant text, joined
    forbid=GATE_FORBID, # Phrases that must not appear in visible text
):
    "The content problems that disqualify a round from becoming a template, whichever host played it"
    probs = []
    if (n := sum(bool(re.match(_START_RE, c)) for c in cells)) != 1: probs.append(f'{n} dojo_start calls')
    if (n := sum(bool(re.match(r'^dojo_score\(', c)) for c in cells)) != 1: probs.append(f'{n} dojo_score calls (a clean round scores once, first try)')
    if any(re.match(r'^dojo_(?:redo|resume)\(', c) for c in cells): probs.append('needed a redo')
    if not any('Clean round' in o for o in outs): probs.append('no clean score')
    if (bad := [f for f in forbid if f in visible]): probs.append(f"script leaked into visible text: {', '.join(bad)}")
    return probs

# %% ../nbs/02_tmpl.ipynb #973e791f
_BOOT_RE = r'^(doc\([^()\n]*\)|list_pyskills\(\))\s*$'

def capture_slice(
    cells, # Kernel cell sources of a conversation's calls, in order
):
    "The `(boot, start, last)` cell indices of a captured dialog: the bootstrap reads before the last dealt round, that round's `dojo_start()`, and its first score"
    starts = [i for i,c in enumerate(cells) if re.match(_START_RE, c)]
    if not starts: raise ValueError('no dojo_start() call')
    start = boot = starts[-1]
    while boot and re.match(_BOOT_RE, cells[boot-1].strip()): boot -= 1
    if boot == start: raise ValueError('no bootstrap doc call before dojo_start()')
    scores = [i for i,c in enumerate(cells[start:], start) if re.match(r'^dojo_score\(', c)]
    if not scores: raise ValueError('no dojo_score() after dojo_start()')
    return boot, start, scores[0]

def boot_gates(
    cells, # A bootstrap reply's kernel cell sources
):
    "The content problems that disqualify a bootstrap reply: a cell that is not a doc read or catalog call, or no doc read at all"
    probs = []
    if (bad := [c for c in cells if not re.match(_BOOT_RE, c.strip())]): probs.append(f'not a bootstrap cell: {bad[0]!r}')
    if not any(c.strip().startswith('doc(') for c in cells): probs.append('no doc() read')
    return probs

# %% ../nbs/02_tmpl.ipynb #8b3b1135
def _turns(
    xs, # Items or records in conversation order
    isprompt, # Is this element a real user prompt?
):
    "`xs` split into user turns at each prompt (a leading group holds anything earlier)"
    xs = L(xs)
    edges = L([0, *xs.argwhere(isprompt), len(xs)])
    return L(xs[s:e] for s,e in edges.pairwise())

# %% ../nbs/02_tmpl.ipynb #c5988523
def doced_names(
    cells, # Kernel cell sources
):
    "Names documented by standalone `doc(...)` calls in `cells`, in both spellings"
    docs = set()
    for c in cells:
        for m in re.finditer(r'(?m)^\s*doc\(([^()\n]+)\)\s*$', c):
            for name in m.group(1).split(','): docs.update(_docnames(name.strip()))
    return sorted(docs)

# %% ../nbs/02_tmpl.ipynb #9b4d0cff
def _pmsgs(dlg): return [m for m in dlg.messages if m.msg_type=='prompt']

def _msg_cells(
    pmsg, # A template prompt message
):
    "`(sub, codes, cells)`: the reply exploded, its code messages, and their kernel cell sources"
    sub = reply2dlg(pmsg)
    codes = [m for m in sub.messages if m.msg_type=='code']
    calls = [_parse_call(m.content) for m in codes]
    if bad := first(m.content for m,c in zip(codes,calls) if not (c and c[1].get('code'))): raise ValueError(f'not a kernel call: {bad}')
    return sub, codes, [c[1]['code'] for c in calls]

def template_cells(
    dlg, # A template dialog
):
    "Kernel cell sources of every prompt's reply in `dlg`, in order"
    return [c for m in _pmsgs(dlg) for c in _msg_cells(m)[2]]

def _one_prompt(m, name):
    "A one-prompt dialog holding a copy of `m`, with `doced` from its own cells"
    d = Dialog(name=name)
    d.mk_message(m.content, msg_type='prompt', output=m.output)
    d.meta['llmdojo'] = dict(doced=doced_names(template_cells(d)))
    return d

def assemble(
    boot, # The host's bootstrap dialog, or its path
    rnd=None, # The shared round dialog, or its path; the packaged round if None
):
    "The template a host splices: the bootstrap's prompt(s), then the round's, with `doced` re-derived over both"
    boot,rnd = [x if isinstance(x, Dialog) else read_ipynb(str(x)) for x in (boot, rnd or ROUND_PATH)]
    d = Dialog(name='dojo_template')
    for m in _pmsgs(boot)+_pmsgs(rnd): d.mk_message(m.content, msg_type='prompt', output=m.output)
    d.meta['llmdojo'] = dict(doced=doced_names(template_cells(d)))
    return d

def split_template(
    dlg, # A two-prompt template dialog: bootstrap, then round
):
    "`(boot, rnd)`: one-prompt dialogs for the bootstrap and the round, each with its own `doced`"
    b,r = _pmsgs(dlg)
    return _one_prompt(b, 'boot'), _one_prompt(r, 'dojo_round')

# %% ../nbs/02_tmpl.ipynb #0b76b9f7
def _replay_cells(
    cells, # Kernel cell sources, run in order
    cwd, # Directory to start the kernel in
    env=None, # Extra environment entries for the kernel process
):
    "Each cell's rendered response from a fresh `clikernel` CLI at `cwd`"
    p = subprocess.Popen(['clikernel'], cwd=str(cwd), env=os.environ|(env or {}), text=True,
        stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
    def upto(stop):
        res = []
        for line in p.stdout:
            if (line := line.rstrip('\n')) == stop: return res
            res.append(line)
        raise RuntimeError(f'clikernel exited during replay; last lines: {res[-5:]}')
    upto(_CLIK_MARKER)
    delim = p.stdout.readline().rstrip('\n')
    outs = []
    for c in cells:
        p.stdin.write(f'--\n{c}\n{delim}\n')
        p.stdin.flush()
        if (ack := p.stdout.readline().rstrip('\n')) != '.': raise RuntimeError(f'expected ack, got {ack!r}')
        outs.append('\n'.join(upto(delim)))
    p.stdin.write('exit\n')
    p.stdin.flush()
    p.wait()
    return outs

# %% ../nbs/02_tmpl.ipynb #fe718d53
DOJO_CANON = '/tmp/dojo'

def canon_tmpl(
    dlg, # A template dialog
    canon=DOJO_CANON, # Canonical spelling for the round's run-dir path
):
    "Rewrite the round's run-dir path (read from its own `%cd` cell) to `canon` throughout every reply, so stored templates read the same on every machine"
    rd = first(re.findall(r"%cd ([^\s'\"\\]+)", ' '.join(m.ai_res for m in _pmsgs(dlg))))
    if rd and rd != canon:
        for m in _pmsgs(dlg): m.output = prompt_output(m.ai_res.replace(rd, canon))
    return dlg

def localized_cells(
    dlg, # A template dialog
):
    "Per prompt, the reply's kernel cells with the canonical run dir localized to this machine's, ready to replay"
    from llmdojo.dojo import _run_dir
    return [[c.replace(DOJO_CANON, str(_run_dir())) for c in _msg_cells(m)[2]] for m in _pmsgs(dlg)]

def refresh_dialog(
    dlg, # A template dialog
    outs, # Per prompt, each cell's fresh output text, as `localized_cells` orders them
    tool=None, # Rename every call to this tool name (a host whose tool is not clikernel's)
):
    "Splice fresh outputs into `dlg`'s baked calls, gate each reply, re-derive `doced`, and canonicalize; returns `dlg`"
    from llmdojo.dojo import _run_dir
    for pm,o in zip(_pmsgs(dlg), outs):
        sub,codes,cells = _msg_cells(pm)
        for m,c,x in zip(codes, cells, o):
            name = tool or _parse_call(m.content)[0]
            if tool: m.content = f'{tool}(code={c.replace(str(_run_dir()), DOJO_CANON)!r})'
            m.output = code_output(x or f'({name} completed with no output)')
        notes = ' '.join(m.content for m in sub.messages if m.msg_type=='note')
        probs = round_gates(cells, o, notes) if any(re.match(_START_RE, c) for c in cells) else boot_gates(cells)
        if probs: raise ValueError('; '.join(probs))
        pm.output = prompt_output(dlg2reply(sub).replace(str(_run_dir()), DOJO_CANON))
    dlg.meta['llmdojo'] = dict(doced=doced_names(template_cells(dlg)))
    return dlg

def refresh_template(
    src, # Path to a template dialog .ipynb
    dst=None, # Where to write the refreshed dialog; `src` if None
):
    "Replay `src`'s kernel cells through a fresh clikernel, splice in current outputs, refresh `doced`, and gate; writes and returns the refreshed dialog"
    dlg = read_ipynb(str(src))
    with tempfile.TemporaryDirectory(prefix='dojorefresh_') as td:
        proj = Path(td)
        (proj/'pyproject.toml').write_text('[project]\nname = "dojo-refresh"\nversion = "0"\n')
        outs = [_replay_cells(cells, proj) for cells in localized_cells(dlg)]
    refresh_dialog(dlg, outs)
    write_ipynb(dlg, str(dst or src))
    return dlg

# %% ../nbs/02_tmpl.ipynb #c181ac72
def launch_config(
    app, # Host tool name ('claude' or 'codex'): config at `$XDG_CONFIG_HOME/<app>dojo/config.toml`
    cfg=None, # Config file path, overriding the `app` default
):
    "Extra `app` args from the config file's `<app>_args` list, each `~`-expanded"
    if cfg is None: cfg = Path(os.environ.get('XDG_CONFIG_HOME') or '~/.config').expanduser()/f'{app}dojo'/'config.toml'
    if not Path(cfg).exists(): return []
    return [os.path.expanduser(o) for o in tomllib.loads(Path(cfg).read_text()).get(f'{app}_args', [])]

# %% ../nbs/02_tmpl.ipynb #b31d935a
@call_parse
def main(
    claude:bool=False, # Build only the Claude store, without refreshing
    codex:bool=False, # Build only the Codex store, without refreshing
    ipyai:bool=False, # Build only the ipyai store (its bootstrap and the round replayed through ipyai's `py`), without refreshing
):
    "Refresh the packaged clikernel dialogs (the shared round and the clikernel bootstrap, replayed through a fresh clikernel), then build every store"
    from llmdojo import claudedojo, codexdojo, ipyaidojo
    builds = dict(claude=claudedojo, codex=codexdojo, ipyai=ipyaidojo)
    only = [n for n,f in dict(claude=claude, codex=codex, ipyai=ipyai).items() if f]
    if not only:
        for p in (ROUND_PATH, CLIK_BOOT):
            refresh_template(p)
            print(f'refreshed: {p}')
    for n in only or builds:
        b = builds[n]
        r = b.build_template()
        if n == 'ipyai': asyncio.run(r)   # the ipyai replay is async (it drives a live kernel through ipyai's own client)
        print(f'built: {n} store ({b.TMPL_DIR})')
